### ISSUE TITLE
artisan blueprint:build returns ErrorException

### ISSUE THREAD

**Issue by jassehomar** [laravel-shift/blueprint#132]
Hi good folks,  I kindly need help with this issue: I created a draft.yaml file in my project root directory. Below is the content of my ymal file.

```yaml
models:
  Video:
    title: string
    synopsis: longtext nullable
    duration: decimal:0,2

  Comment:
    user_id: id
    content: longtext
    approved: boolean

  Watch:
    user_id: id
    video_id: id
    completed_at: datetime
    timestamp: false
```

when I run artisan blueprint:build I received this error below

```bash
  ErrorException 

  str_repeat(): Second argument has to be greater than or equal to 0

  at vendor/laravel-shift/blueprint/src/Generators/FactoryGenerator.php:103
     99|                 $scale = min([30, max([0, intval($column->attributes()[1] ?? 0)])]);
    100| 
    101|                 $definition = str_replace(
    102|                     "/** {$column->dataType()}_attributes **/",
  > 103|                     implode(', ', [$scale, 0, (str_repeat(9, $precision - $scale) . '.' . str_repeat(9, $scale))]),
    104|                     $definition
    105|                 );
    106|             } elseif ($column->dataType() === 'json') {
    107|                 $default = $column->defaultValue() ?? "'{}'";

      +20 vendor frames 
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

```
