### ISSUE TITLE
Extending Blueprint's definitions through addons

### ISSUE THREAD

**Issue by Naoray** [laravel-shift/blueprint#133]
As mentioned in #68 it's easy to write an addon which registers its own `Generator` and interprets the given definitions parsed by blueprints existing `Lexers`. The more I think about extending the functionality of Blueprint beyond simply generating content the more questions arise when thinking about how to add new definitions to the `draft.yaml` file.

For [nova addon](https://github.com/Naoray/blueprint-nova-addon) e.g. I'd like to add definitions which let the user define if a relationship is `->searchable()`. Using this example here are some options on how we could solve this 'issue'.

---

The easiest for the user would be to simply merge the definitions with the original blueprint definitions like adding a searchable to the field definition. 

:-1: This could cause a lot of confusion and probably errors from the `blueprint:build` command.

```yaml
models:
  Post:
    author_id: id:user searchable
    # other field definitions

  Comment:
    post_id: id searchable
    # other field definitions
```

---

This option adds a new namespace for each addon to add new definitions.

:+1: The existing `Lexers` would not pick up on the addon's definitions

:-1:  The user has to write more lines of yaml which in the case of an nova addon means kind of repeating the model definitions all over again
:-1: It's still not save to say if blueprint could add the same definition some time in the future which would cause some weird behaviour

```yaml
models:
  Post:
    author_id: id:user
    # other field definitions

  Comment:
    post_id: id
    # other field definitions
    
nova:
  Post:
    author: searchable
  
  Comment:
    post: searchable
```

---
This option adds a separate definition for addon definitions.

:+1: The existing `Lexers` would not pick up on the addon's definitions
:+1: It's save to say that blueprint won't interpret these definitions

:-1:  The user has to write more lines of yaml
:-1: Different addons could use the same name definitions

```yaml
models:
  Post:
    author_id: id:user
    # other field definitions

  Comment:
    post_id: id
    
addons:
  nova:
    Post:
      author: searchable

    Comment:
      post: searchable
```

---

Any other ideas or thoughts on how to guide the community when creating addons?
