### ISSUE TITLE
softDeletes not working

### ISSUE THREAD

**Issue by MeowKim** [laravel-shift/blueprint#138]
Hello there.  
I'm new to here and following README to experience blueprint world.  

![error_blueprint_softdeletes_00](https://user-images.githubusercontent.com/22974628/79933429-f6d92280-848a-11ea-8e34-3a18be7354b8.jpg)

When I add **softDeletes** to model in yaml, it throws parse exception like below.  

![error_blueprint_softdeletes](https://user-images.githubusercontent.com/22974628/79933166-33584e80-848a-11ea-8af8-9f6d90dda814.jpg)

I saw related issue [#45](https://github.com/laravel-shift/blueprint/issues/45), seems that this is fixed.  
But no good with shorthands for me. It works good with valid yaml syntax like **softDeletes: true**.  

Is this feature(shorthands) unavailable now?

**Comment by MeowKim** [comment]
aw....  
I didn't check generated codes.
**softDeletes: true** generates softDeletes column.  
  
![error_blueprint_softdeletes_02](https://user-images.githubusercontent.com/22974628/79934288-29841a80-848d-11ea-94a4-759b9408e483.jpg)

**Comment by nathane** [comment]
Hey @MeowKim,

I just ran the same config but I was not able to reproduce the bug that you experienced. It might be a composer issue. What versions of Laravel and Blueprint are you using?

```yaml
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp
  Comment:
    content: longtext
    published_at: nullable timestamp
    user_id: id
    softDeletes

controllers:
  Post:
    index:
      query: all
      render: post.index with:posts

    store:
      validate: title, content
      save: post
      send: ReviewNotification to:post.author with:post
      dispatch: SyncMedia with:post
      fire: NewPost with:post
      flash: post.title
      redirect: post.index
```
![image](https://user-images.githubusercontent.com/9754361/79936431-78966500-8425-11ea-8108-3d2d1f333e86.png)
