### ISSUE TITLE
Support for Custom Namespace

### ISSUE THREAD

**Issue by ManojKiranA** [laravel-shift/blueprint#14]
In most of the time Every Devs prefers to keep the models and Controllers based on their groups
So For Example i have a app that contains the Blog so i wish to keep the Models inside the `app/Models/Blog` so this below syntax might be helpful in many situation because i see most of the app that is Built with laravel has the models inside the **app/Models** Directory

```
models:
  Models/Blog/Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp

controllers:
  Blog/PostController:
    index:
      query: all posts
      render: post.index with posts

    store:
      validate: title, content
      save: post
      send: ReviewNotification to post.author
      queue: SyncMedia
      flash: post.title
      redirect: post.index
```
