### ISSUE TITLE
belongsToMany (pivot) relation generates the first column capitalized.

### ISSUE THREAD

**Issue by mikevandiepen** [laravel-shift/blueprint#140]
Hi,

I was testing out blueprints and I tried generating a pivot relation (Which by the way is not documented in the `README.MD`.) and I noticed that the migration failed. When I tried looking into it I noticed that the first column of the migration is capitalized.

**create_schedule_workout_table.php**
```php
    public function up()
    {
        Schema::create('schedule_workout', function (Blueprint $table) {
            $table->bigIncrements('Schedule_id');
            $table->bigIncrements('workout_id');
        });
    }
```

**draft.yaml**
```yml
models:
  Schedule:
    name: String:255
    timestamps: false
    relationships:
      belongsToMany: Workout

  Workout:
    name: String:255
    timestamps: false
    relationships:
      belongsToMany: Schedule
```

**Error message**
```
 Error 

  Class 'CreateScheduleWorkoutTable' not found

  at E:\Development\BluePrintTest\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:453
    449|     public function resolve($file)
    450|     {
    451|         $class = Str::studly(implode('_', array_slice(explode('_', $file), 4)));
    452| 
  > 453|         return new $class;
    454|     }
    455| 
    456|     /**
    457|      * Get all of the migration files in a given path.

  1   E:\Development\BluePrintTest\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:189
      Illuminate\Database\Migrations\Migrator::resolve("2020_04_23_214917_create_schedule_workout_table")

  2   E:\Development\BluePrintTest\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:165
      Illuminate\Database\Migrations\Migrator::runUp("E:\Development\BluePrintTest\database\migrations/2020_04_23_214917_create_schedule_workout_table.php")
```

I tested it with different model names but the issue still occurred.
