### ISSUE TITLE
Wrong http method in destroy_deletes TestCase

### ISSUE THREAD

**Issue by Pr3d4dor** [laravel-shift/blueprint#142]
Using the following config:

```
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp

controllers:
  Post:
    index:
      query: all
      render: post.index with:posts

    store:
      validate: title, content
      save: post
      send: ReviewNotification to:post.author with:post
      dispatch: SyncMedia with:post
      fire: NewPost with:post
      flash: post.title
      redirect: post.index

    destroy:
      delete: post
      fire: PostDeletedEvent with:post
```

The generated test case `destroy_deletes` is:

```
    /**
     * @test
     */
    public function destroy_deletes()
    {
        $post = factory(Post::class)->create();
        $post = factory(Post::class)->create();

        Event::fake();

        $response = $this->get(route('post.destroy', $post));

        $this->assertDeleted($post);

        Event::assertDispatched(PostDeletedEvent::class, function ($event) use ($post) {
            return $event->post->is($post);
        });
    }
```

As you can see the HTTP method being used is "GET", but the correct method should be "DELETE".
