### ISSUE TITLE
Infer foreign reference from `id` modifiers

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#156]
As noted in #154, there is an incomplete boundary case where the foreign key reference could be inferred from the `id` modifier.

For example, given the column definition:

```yaml
models:
  Team:
    user_id: id
    owner_id: id:user
```

If `use_constraints` were enabled, Blueprint should generate the proper foreign key constraint from the `id` modifier `user`. Currently it would incorrectly reference `owners` as pulled from the column name.
