### ISSUE TITLE
Add ability to customize pivot columns

### ISSUE THREAD

**Issue by kennyhorna** [laravel-shift/blueprint#175]
Hi, amazing work by the way!

### Current situation

Reviewing the docs I can see that you can specify `belongsToMany` relationships like so:

```yaml
# draft.yaml

models:
  User:
    ...
    relationships:
      belongsToMany: Store
```

This will generate something similar to the following method in the `User` model:

```php
# User.php

public function stores()
{
    return $this->belongsToMany(Store::class);
}
```
But, currently, there's no way to customize the pivot table name: `store_user`

### Proposal

It could be possible to pass an attribute when specifying the relationship to customize the pivot table:

```yaml
models:
  User:
    ...
    relationships:
      belongsToMany: Store:favorites
```

Generating:

```php
# User.php

public function stores()
{
    return $this->belongsToMany(Store::class, 'favorites');
}
```

**Even further**, in case you specify the pivot colum as a PascalCase word, this could generate the pivot model and configure it in the related models:

```yaml
#draft.yaml

models:
  User:
    ...
    relationships:
      belongsToMany: Store:Favorite
```

```php
# User.php

public function stores()
{
    return $this->belongsToMany(Store::class)->using(Favorite::class);
}
```
