### ISSUE TITLE
Faker code for biginteger not generated

### ISSUE THREAD

**Issue by ahawlitschek** [laravel-shift/blueprint#177]
When using the type `biginteger` in a model, the factory leaves an empty arrow:

```yaml
Contract:
    issued_at: date
    number: biginteger
    type: enum:creator,contributor
    status: enum:overdue,paid,disputed
    relationships:
      hasMany: ContractPosition
      belongsTo: Work
```

```php
<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Contract;
use Faker\Generator as Faker;

$factory->define(Contract::class, function (Faker $faker) {
    return [
        'issued_at' => $faker->date(),
        'number' => $faker->,
        'type' => $faker->randomElement(["creator","contributor"]),
        'status' => $faker->randomElement(["overdue","paid","disputed"]),
    ];
});
```

This is caused by the mapping table in the factory generator:

![image](https://user-images.githubusercontent.com/53199186/80988143-57754180-8e33-11ea-87b0-6afe5961522c.png)

Instead of `biginteger`, the key `bigint`is used
