### ISSUE TITLE
Problem when generating a factory to a model has relationship

### ISSUE THREAD

**Issue by MOHAMMED-ABD-RAZAQ** [laravel-shift/blueprint#182]
this generated factory from draft.yaml file 

![image](https://user-images.githubusercontent.com/29556066/81022038-2df1ff80-8e9f-11ea-85f8-c1f4a9398326.png)

but when run seed for this factory i got error 

![image](https://user-images.githubusercontent.com/29556066/81021955-f97e4380-8e9e-11ea-8105-ceacc6402352.png)

so every time i build blue print i should remove the id and Plural \`s
from this `'customer_id' => factory(\App\Customers.id::class),`
to be like this `'customer_id' => factory(\App\Customer::class),`
so it should build factory class without Plural and constant id

**Comment by jasonmccreary** [comment]
Yeah, seems like there's a bug with the factory generator and model reference.

Could you share the `models` section of your draft file for recreation.

**Comment by jasonmccreary** [comment]
I was unable to recreate this with the following draft file:

```yaml
models:
  Point:
    customer_id: id
    partner_id: id
    status: boolean
    price: decimal:7,0
```

My guess is you're doing something like:

```yaml
models:
  Point:
    customer_id: id:customers.id
    partner_id: id:partners.id
    # ...
```

Which, while an explicit syntax, is unnecessary and no need to type all that out with Blueprint when using conventions.

Nonetheless, #158 is open to support the unconventional cases where you may _need_ to use such an explicit syntax.
