### ISSUE TITLE
Missing `update` statement

### ISSUE THREAD

**Issue by andreich1980** [laravel-shift/blueprint#185]
I couldn't find any `Controller@update` method example in the docs, only `store()`.

Although the docs say that Blueprint supports `update` statement, I couldn't make it work.

My `draft.yaml`
``` yaml
models:
  Program:
    title: string

controllers:
  Program:
    store:
      validate: title
      save: program
      redirect: program.show
    update:
      validate: title
      save: program # I have tried `update: program`, too
      redirect: program.show
```

Generated controller methods:
```php
    public function store(ProgramStoreRequest $request)
    {
        $program = Program::create($request->all());
        return redirect()->route('program.show', ['program' => $program]);
    }
    public function update(ProgramUpdateRequest $request, Program $program)
    {
        $program->save(); // When I use `update: program` there's no action at all, just a redirect.

        return redirect()->route('program.show', ['program' => $program]);
    }
```

What am I missing here?
