### ISSUE TITLE
Generated migration includes extra parenthesis

### ISSUE THREAD

**Issue by kreeves** [laravel-shift/blueprint#194]
Steps to reproduce:

1. Create draft.yaml file like below
```yaml
  Team:
    name: string:400

  ScheduledGame:
    homeTeam: id foreign:teams
    awayTeam: id foreign:teams
    scheduled: dateTimeTz
```
2. Run `php artisan blueprint:build`
3. Run `php artisan migrate`
4. Observed behavior:
<details>
<summary>Expand to see error.</summary>

>   ParseError
> 
>   syntax error, unexpected ')'
> 
>   at database/migrations/2020_05_08_142800_create_scheduled_games_table.php:18
>     14|     public function up()
>     15|     {
>     16|         Schema::create('scheduled_games', function (Blueprint $table) {
>     17|             $table->id();
>   > 18|             $table->foreignId('homeTeam')->constrained('teams', 'homeTeam')->cascadeOnDelete());
>     19|             $table->foreignId('awayTeam')->constrained('teams', 'awayTeam')->cascadeOnDelete());
>     20|             $table->dateTimeTz('scheduled');
>     21|             $table->timestamps();
>     22|         });
> 
>       +19 vendor frames
>   20  artisan:37
>       Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

</details>
