### ISSUE TITLE
[Idea] Separate migration for foreign keys

### ISSUE THREAD

**Issue by tabacitu** [laravel-shift/blueprint#208]
First of all @jasonmccreary - I'm just blown away by how cool this is. Great work!

---

When generating migrations, it's pretty easy to end up with files that will NOT migrate - because you have foreign keys towards tables that don't exist yet. This is not a Blueprint problem per-se, it's an inconvenience in migrations. But it's a common one, and something that _maybe_ we can fix using Blueprint.

### Synopsis:

Imagine an Articles-Categories-Tags setup for a simple blog:

```yaml
models:
  Article:
    category_id: id foreign # this will fail - there is no Category yet
    title: string
    slug: string unique default:''
    content: text
    image: string nullable
    status: enum:PUBLISHED,DRAFT
    date: date
    featured: boolean default:0
    timestamps: true
    softDeletes: true
    relationships:
      belongsToMany: Tag # this will fail - there is no Tag yet
      
  Category:
    parent_id: id foreign:categories
    left: integer unsigned nullable
    right: integer unsigned nullable
    depth: integer unsigned nullable
    name: string
    slug: string unique
    timestamps: true
    softDeletes: true
    relationships:
      hasMany: Article

  Tag:
    name: string
    slug: string unique
    timestamps: true
    softDeletes: true
    relationships:
      belongsToMany: Article

seeders: Article, Category, Tag

``` 

### Expected Behavior:

Personally, I'd expect the above to work fine - both Models and relationships to be properly defined, and be able to run them successfully.

### Actual Behavior:

With the above, the generated models are perfect. But the migrations can't be run:

![Screenshot 2020-05-15 at 10 26 21](https://user-images.githubusercontent.com/1032474/82023206-9490cd80-9696-11ea-8ce7-08a5591e6b5e.png)

Again, the problem is that the **foreign keys point to tables that don't exist yet**. 

There's a quick workaround in the example above: just move `Category` before `Article`, and/or disable foreign keys in Blueprint. This works for this example, but I don't think it'll work for all use cases. If `Category` was dependant on `Tag` too, then there would be no solution for this problem.

### Proposed Syntax:

What if, when generating the migrations, Blueprint just _ignored_ the foreign keys at first pass? Then at the very end, after having generated the migrations for the actual tables, it would generate **a separate migration, only for foreign keys, for all tables**?

The way I see it, this would:
- fix the "_chicken or the egg_" problem;
- require zero syntax change;
- developers won't have to worry about the order their Models are in, which I think makes for a great Developer Experience;

---

What do you think about this @jasonmccreary ? Would this make sense inside Blueprint? Would it be a difficult change?

I think I can dedicate some time in the next 2-3 weeks to understand how Blueprint works and submit a PR, if it's something you don't want to do yourself, but it's something worth doing 😄 

Cheers!
