### ISSUE TITLE
yaml parsing bug

### ISSUE THREAD

**Issue by vootrunner** [laravel-shift/blueprint#214]
- Laravel Version: #.#.#
- PHP Version: 7.4.4
- Blueprint Version: 7.11.0
- Platform: Mac

### Description:
Malformed yaml causes the ModelLexer to throw PHP errors.

### Steps To Reproduce:

simplified draft.yaml with an incorrect indentation for ModelB:

```
models:
  modelA:
    softDeletes
    media: string:100 index unique
    relationships:
      hasMany: ModelB

    ModelB:
      softDeletes
      genre: string:100 index unique
```

```
$ php artisan blueprint:build

   TypeError

  Argument 2 passed to Blueprint\Lexers\ModelLexer::buildColumn() must be of the type string, array given, called in /Sites/libra/vendor/laravel-shift/blueprint/src/Lexers/ModelLexer.php on line 165

  at vendor/laravel-shift/blueprint/src/Lexers/ModelLexer.php:180
    176|
    177|         return $model;
    178|     }
    179|
  > 180|     private function buildColumn(string $name, string $definition)
    181|     {
    182|         $data_type = 'string';
    183|         $modifiers = [];
    184|

      +19 vendor frames
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
