### ISSUE TITLE
Invalid chaining of `nullable` for `foreignId`

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#215]
- Laravel Version: 7.0.0
- PHP Version: 7.4
- Blueprint Version: 1.11.0
- Platform: Mac

### Description:
This is a bug pulled from [#213](https://github.com/laravel-shift/blueprint/issues/213#issuecomment-630075982) regarding the order of `nullable`.

In Laravel 7.0, it needs to immediately follow the `foreignId`, otherwise it will generate an error.

### Steps To Reproduce:
Here is an example draft file which should yield a migration with the invalid chaining.

```yaml
models:
  Cart:
    name: string
    user_id: id foreign nullable
```
