### ISSUE TITLE
Draft file creates  API routes when using 'resource'

### ISSUE THREAD

**Issue by twoarmtom** [laravel-shift/blueprint#225]
- Laravel Version: 6.13.1
- PHP Version 7.2.19
- Blueprint Version: 1.11
- Platform: Windows

### Description:
The draft.yaml file creates api routes instead of web routes when using the shorthand 'resource' then running php artisan blueprint:build

### Steps To Reproduce:
Using the following in the draft.yaml file:

### draft.yaml:
```yaml
models:
  Page:
    page_name: string
    page_slug: string
    page_content: longtext
    order: integer nullable

  File:
    file_name: string
    file_path: text
    relationships:
      belongsToMany: Category

  Category:
    category_name: string
    relationships:
      belongsToMany: File

  Gallery:
    gallery_name: string
    images: longtext
    order: integer nullable

controllers:
  Page: 
    resource
  
  File:
    resource

  Category:
    resource

  Gallery:
    resource
```
