### ISSUE TITLE
rememberToken is generating a empty faker

### ISSUE THREAD

**Issue by coldKingdom** [laravel-shift/blueprint#228]
- Laravel Version: 7.12.0
- PHP Version: 7.4.6
- Blueprint Version: 1.12.0
- Platform: Windows | Linux (WSL)

### Description:
I have a remember_token column in the User-migration.
When generating that one, it generates an empty $faker-> .
Would it be possible to set it to the default 'remember_token' => Str::random(10), or maybe $faker->asciify(10) ?

#### One more small request (not that it's really needed):
Would it be possible to just write remember_token without the column name to generate $table->rememberToken(); like in the original migration?

### Steps To Reproduce:
Run the buildprint:build with my draft.yaml :)

### draft.yaml:
```yaml
models:
  User:
    name: string
    email: string unique
    email_verified_at: datetime nullable
    password: string
    remember_token: remembertoken
```
### Suggested draft.yaml for the small request
```yaml
models:
  User:
    name: string
    email: string unique
    email_verified_at: datetime nullable
    password: string
    remember_token:
```
