### ISSUE TITLE
Request: Import Authenticatable in models

### ISSUE THREAD

**Issue by coldKingdom** [laravel-shift/blueprint#237]
### Synopsis:
Using auth scaffolding in Laravel or the default User-model. The model imports
```php
use Illuminate\Foundation\Auth\User as Authenticatable;
```
So when running blueprint:erase and blueprint:build, it removes that import every time.

### Proposed Syntax:
In the draft.yaml it would be nice to be able to do something like:
```yaml
models:
  User:
    name: string
    email: string unique
    email_verified_at: datetime nullable
    password: string
    remember_token: rememberToken
    authenticatable
```

#### Before
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model {
```

#### After
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable {
```
