### ISSUE TITLE
Resource: api.store is being added to web.php instead of api.php

### ISSUE THREAD

**Issue by dishereandy** [laravel-shift/blueprint#241]
- Laravel Version: 7.12.0
- PHP Version: 7.4.3
- Blueprint Version: 1.12
- Platform: Windows

### Description:
Resources are not added as api routes when using resource: api.store, api.destroy. 

### Steps To Reproduce:
Run blueprint:build

### draft.yaml:
```yaml
controllers:
  UserController:
      resource: api.store, api.show, api.update
```
