### ISSUE TITLE
Basic example config incorrect? post.author is not defined

### ISSUE THREAD

**Issue by dmason30** [laravel-shift/blueprint#248]
Majority of users will copy this config to first run the `blueprint:build` to get a feel for how it is done. This is the current example that is on the README and on the documentation site.  

```yaml
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp

controllers:
  Post:
    index:
      query: all
      render: post.index with:posts

    store:
      validate: title, content
      save: post
      send: ReviewNotification to:post.author with:post
      dispatch: SyncMedia with:post
      fire: NewPost with:post
      flash: post.title
      redirect: post.index
```

However, the `post.author` in the `ReviewNotification` has not been defined and results in the `PostControllerTest::store_saves_and_redirects` generated test failing with error: 

```sh
ErrorException: Trying to get property 'email' of non-object in file
.../vendor/laravel/framework/src/Illuminate/Mail/Mailable.php on line 605
```

This is because the author relation has not been defined and after that would need top be added top the `validate` section.
