### ISSUE TITLE
Unable to resolve error message

### ISSUE THREAD

**Issue by Wulfheart** [laravel-shift/blueprint#251]
- Laravel Version: 7.13.0
- PHP Version: 7.2.19
- Blueprint Version: 1.13.0
- Platform: Mac | Windows | Linux

### Description:
````
PS Some:\Path\To\Project> php artisan blueprint:build 

   TypeError 

  Argument 2 passed to Blueprint\Lexers\ModelLexer::buildColumn() must be of the type string, array given, called in Some:\Path\To\Project\vendor\laravel-shift\blueprint\src\Lexers\ModelLexer.php on line 174

  at Some:\Path\To\Project\vendor\laravel-shift\blueprint\src\Lexers\ModelLexer.php:204
    200| 
    201|         return $model;
    202|     }
    203| 
  > 204|     private function buildColumn(string $name, string $definition)
    205|     {
    206|         $data_type = null;
    207|         $modifiers = [];
    208| 

  1   Some:\Path\To\Project\vendor\laravel-shift\blueprint\src\Lexers\ModelLexer.php:174
      Blueprint\Lexers\ModelLexer::buildColumn("0", ["string"])

  2   Some:\Path\To\Project\vendor\laravel-shift\blueprint\src\Lexers\ModelLexer.php:109
      Blueprint\Lexers\ModelLexer::buildModel()
````

### draft.yaml:
[Check out this gist](https://gist.github.com/Wulfheart/895500828d27287faf6d37be04bad58f)

**Comment by Pr3d4dor** [comment]
The problem is that you used "- " in the model columns definitions. 

This draft.yml works fine:
```
models:
  BaseBuilding:
    name: string
    min_level: unsignedInteger
    max_level: unsignedInteger
    time_bonus: float:8,2
    resource_bonus: float:8,2
    build_base_time: unsignedInteger
    ore_cost: unsignedInteger
    food_cost: unsignedInteger
    energy_cost: unsignedInteger
    people_cost: unsignedInteger
    ore_maintenance_cost: unsignedInteger
    food_maintenance_cost: unsignedInteger
    energy_maintenance_cost: unsignedInteger
    people_maintenance_cost: unsignedInteger
    ore_production: unsignedInteger
    food_production: unsignedInteger
    energy_production: unsignedInteger
    people_production: unsignedInteger
    production_growth: float:8,2
    cost_growth: float:8,2
    maintenance_cost_growth: float:8,2
    ship_build_time_bonus: float:8,2
    ship_build_cost_bonus: float:8,2
    can_build_ships: boolean
  BaseShip:
    name: string
    ore_build_cost: unsignedInteger
    food_build_cost: unsignedIntegergit
    energy_build_cost: unsignedInteger
    people_build_cost: unsignedInteger
    ore_maintenance_cost: unsignedInteger
    food_maintenance_cost: unsignedInteger
    energy_maintenance_cost: unsignedInteger
    people_maintenance_cost: unsignedInteger
    storage_capacity: unsignedInteger
    attack_strength: unsignedInteger
    defense_strength: unsignedInteger
    scientific: boolean
    build_time: unsignedInteger
    travel_speed_sublight: float:8,2
    travel_speed_hyper: float:8,2
  BuildingRequirements:
    building_id: unsignedBigInteger
    required_building_id: unsignedBigInteger
    required_building_level: unsignedInteger
  ShipRequirements:
    base_ship_id: unsignedBigInteger
    required_building_id: unsignedBigInteger
    required_building_level: unsignedInteger
  System:
    x_position: integer
    y_position: integer
    z_position: integer
    accessible: boolean
    color: enum:red,orange,yellow,white,blue
  Planet:
    system_id: unsignedBigInteger
    number: unsignedInteger
    name: string
    owner_id: unsignedBigInteger
    planet_type_id: unsignedBigInteger
  PlanetType:
    name: string
    ore_cost_factor: float:8,2
    food_cost_factor: float:8,2
    energy_cost_factor: float:8,2
    people_cost_factor: float:8,2
    ore_gain_factor: float:8,2
    food_gain_factor: float:8,2
    energy_gain_factor: float:8,2
    people_gain_factor: float:8,2
    start_percentage: float:8,2
    end_percentage: float:8,2
  Building:
    base_building_id: unsignedBigInteger
    planet_id: unsignedBigInteger
    level: unsignedInteger
  Ship:
    base_ship_id: unsignedBigInteger
    name: string
    owner_id: unsignedBigInteger
    ore_stored: unsignedInteger
    food_stored: unsignedInteger
    energy_stored: unsignedInteger
    people_stored: unsignedInteger
    fleet_id: unsignedBigInteger
  Fleet:
    name: string
    planet_id: unsignedBigInteger
    home_planet_id: unsignedBigInteger
    owner_id: unsignedBigInteger
  Mission:
    type: enum:exploration,attack,invasion,raid,transport,transfer
    target_system_id: unsignedBigInteger
    target_planet_id: unsignedBigInteger
    fleet_id: unsignedBigInteger
    arrival: dateTime
    finished: dateTime
    return: dateTime
  Report:
    fleet_id: unsignedBigInteger nullable
    subject: string
    content: longtext
    readable_from: dateTime
  Message:
    sender_id: unsignedBigInteger
    receiver_id: unsignedBigInteger
    subject: string
    content: longtext
    readable_from: dateTime
  Policy:
    user_id: unsignedBigInteger
    system_access: enum:none,whitelist,blacklist,everybody
    foreign_system_access: enum:force,respect
    first_contact: enum:share_contact_details,enigmatic
  SystemAccess:
    user_id: unsignedBigInteger
    target_user_id: unsignedBigInteger
    type: enum:whitelist,blacklist
  BuildQueue:
    building_id: unsignedBigInteger
    finishes_at: dateTime
    duration: string
  ShipQueue:
    base_ship_id: unsignedBigInteger
    planet_id: unsignedBigInteger
    finishes_at: dateTime
    duration: string
```

I don't know if this should be treated as a bug or not.
