### ISSUE TITLE
FactoryGenerator bug for smallInteger and tinyInteger fields

### ISSUE THREAD

**Issue by mixartemev** [laravel-shift/blueprint#255]
- Laravel Version: 7.13.0
- PHP Version: 7.4.6
- Blueprint Version: dev-master
- Platform: Mac

### Description:
Fake values aren't generates in Factory for smallInteger and tinyInteger fields:
<img width="501" alt="Screenshot 2020-05-31 at 18 40 27" src="https://user-images.githubusercontent.com/5181924/83356599-d0eb4b80-a36f-11ea-98a1-6373c1241b4e.png">

### Steps To Reproduce:
1. Make draft.yaml like in my exmple bottom
2. run `php artisan blueprint:build`

### draft.yaml:
```yaml
models:
  Model:
    market_type: tinyInteger
    deposit: smallInteger unsigned
```
