### ISSUE TITLE
FormRequestGenerator bug with nullable fields

### ISSUE THREAD

**Issue by mixartemev** [laravel-shift/blueprint#258]
- Laravel Version: 7.13.0
- PHP Version: 7.4.6
- Blueprint Version: dev-master
- Platform: Mac

### Description:
For nullable fields generates required rules In FormRequests

<img width="665" alt="Screenshot 2020-06-01 at 01 00 17" src="https://user-images.githubusercontent.com/5181924/83364204-538ffd00-a3a8-11ea-91d3-9c886d2932b5.png">

### Steps To Reproduce:
1. Make draft.yaml like in my exmple bottom
2. `run php artisan blueprint:build`

### draft.yaml:
```yaml
models:
  Model:
    min: smallInteger nullable
    min_condition: smallInteger nullable
```
