### ISSUE TITLE
Generate fake type data for date types

### ISSUE THREAD

**Issue by dehboris** [laravel-shift/blueprint#261]
- Laravel Version: ^7.0
- PHP Version: 7.4.
- Blueprint Version: ^1.13
- Platform: Windows

### Description:
When i use model data type like `smallInteger` or `year`, in factory the faker not generate all attributes.

### draft.yaml:
```yaml
models:
  File:
    month: smallInteger
    year: year
    path: string
```

###  FileFactory.php
```php
$factory->define(File::class, function (Faker $faker) {
    return [
        'month' => $faker->,
        'year' => $faker->,
        'path' => $faker->word,
    ];
});
```
