### ISSUE TITLE
trace has problem with enums?

### ISSUE THREAD

**Issue by ndeblauw** [laravel-shift/blueprint#262]
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Blueprint Version: 1.13.0
- Mysql 5.7.18 (x64)
- Platform: Windows

### Description:
I generated with blueprint a model that contains enums. When I wanted to check out the trace functionality, I bumped upon the following error:
![image](https://user-images.githubusercontent.com/4344869/84124013-ed0b7e80-aa3a-11ea-8189-1351d04a36eb.png)
The model/migration that is generated 

### Steps To Reproduce:
- **blueprint:build** a simple draft.yaml (see below) with enums
- then do a **blueprint:trace** to see the error

### draft.yaml:
```yaml
models:
  Testmodel:
    name: string:30
    contact_via: enum:mail,sms,phone,whatsapp,messenger default:'phone'
```
