### ISSUE TITLE
field as double in yaml leads to empty faker definition

### ISSUE THREAD

**Issue by ndeblauw** [laravel-shift/blueprint#264]
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Blueprint Version: 1.13.0
- Mysql 5.7.18 (x64)
- Platform: Windows

### Description:
Generating a model with a double field leads to an empty line in the faker library (and thus an error). 

### Steps To Reproduce:
1. Generate a model with a double field in it (e.g. draft yaml below)
2. Check the factory of it, and observe the 
```
[...]
$factory->define(Job::class, function (Faker $faker) {
    return [
        'title' => $faker->sentence(4),
        'compensation_euro' => $faker->,
    ];
});
```

### draft.yaml:
```yaml
models
  Job:
    title: string:100
    compensation_euro: double default:0
```
