### ISSUE TITLE
Controllers not generated, empty namespace

### ISSUE THREAD

**Issue by gmgarrison** [laravel-shift/blueprint#269]
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Blueprint Version: 1.13.0
- Platform: Mac

### Issue:
Controller files are generated with no namespace and empty classes. Models are generated in the root directory. (Am I doing any of this right??)

Also, `php artisan blueprint:build` ends with an error relating to the lack of namespaces, I believe:
```
 TypeError

  Argument 1 passed to Blueprint\Blueprint::relativeNamespace() must be of the type string, null given, called in /srv/fameo/vendor/laravel-shift/blueprint/src/Generators/TestGenerator.php on line 76

  at vendor/laravel-shift/blueprint/src/Blueprint.php:15
    11| {
    12|     private $lexers = [];
    13|     private $generators = [];
    14|
  > 15|     public static function relativeNamespace(string $fullyQualifiedClassName)
    16|     {
    17|         $namespace = config('blueprint.namespace') . '\\';
    18|         $reference = ltrim($fullyQualifiedClassName, '\\');
    19|

```

The error was the only output, so I was surprised to see that the Model files, factories and seeders were all generated. (Models also have no namespace.)

### draft.yaml:
```yaml
# https://blueprint.laravelshift.com/docs/generating-components/
models:
  Enum:
    value: varchar(200)
  EnumCountry:
    value: varchar(200)
  EnumState:
    value: varchar(200)
  Profile:
    state: id foreign:enumState
    country: id foreign:enumCountry
    type: tinyint unsigned index
    status: tinyint unsigned index
    timezone: tinyint unsigned
    softDeletes
  Video:
    owner_id: id foreign:user
    parent_id: id foreign:user
    url: string(150)
    status: tinyint unsigned index
    visibility: tinyint unsigned
    prompt: id foreign:prompt
    size: int unsigned
    length: int unsigned
    views: mediumint unsigned
    softDeletes
  Prompt:
    text: varchar(400)
    type: tinyint unsigned index
    status: tinyint unsigned index
    group: id foreign:promptGroup
    softDeletes
  PromptGroup:
    name: varchar(100)
    type: tinyint unsigned index
    status: tinyint unsigned index
    softDeletes
  PromptSchedule:
    parent_id: id foreign:user
    user_id: id foreign:user
    prompt_id: id foreign:prompt
    video_id: id foreign:video
    status: tinyint unsigned index
    send_date: datetime
    softDeletes
  Family:
    name: varchar(100)
    status: tinyint unsigned index
    softDeletes
  Relation:
    family_id: id foreign:family
    parent_id: id foreign:user
    user_id: id foreign:user
    type: tinyint unsigned
    status: tinyint unsigned
    softDeletes
seeders: Profile, Video, Prompt, PromptGroup, PromptSchedule, Family, Relation
controllers:
  Profile:
    resource: all
  Video:
    resource: all
  Prompt:
    resource: all
  PromptGroup:
    resource: all
  PromptSchedule:
    resource: all
  Family:
    resource: all
  Relation:
    resource: all
```

I also have the blueprint.php config file:
```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Application Namespace
    |--------------------------------------------------------------------------
    |
    | Blueprint uses the default Laravel application namespace of 'App'.
    | However, you may configure Blueprint to use a custom namespace.
    | This value should match a PSR-4 autoload configuration value
    | within the composer.json file of your Laravel application.
    |
    */
    'namespace' => 'App',


    /*
    |--------------------------------------------------------------------------
    | Component Namespaces
    |--------------------------------------------------------------------------
    |
    | Blueprint promotes following Laravel conventions. As such, it generates
    | components under the default namespaces. For example, models are under
    | the `App` namespace. However, you may configure Blueprint to use
    | your own custom namespace when generating these components.
    |
    */
    'models_namespace' => 'Models',
    'controllers_namespace' => 'Http\\Controllers',


    /*
    |--------------------------------------------------------------------------
    | Application Path
    |--------------------------------------------------------------------------
    |
    | By default, Blueprint will save the generated application components
    | under the files under the `app` folder. However, you may configure
    | Blueprint  to save these generated component under a custom path.
    |
    */
    'app_path' => 'app',

    /*
    |--------------------------------------------------------------------------
    | Generate PHPDocs
    |--------------------------------------------------------------------------
    |
    | Here you may enable generate PHPDocs for classes like Models. This
    | not only serves as documentation, but also allows your IDE to
    | map to the dynamic properties used by Laravel Models.
    |
    */
    'generate_phpdocs' => true,

    /*
    |--------------------------------------------------------------------------
    | Foreign Key Constraints
    |--------------------------------------------------------------------------
    |
    | Here you may enable Blueprint to always add foreign key constraints
    | within the generated migration. This will relate these records
    | together to add structure and integrity to your database.
    |
    | In addition, you may specify the action to perform `ON DELETE`. By
    | default Blueprint will use `cascade`. However, you may set this
    | to 'restrict', 'no_action', or 'null' as well as inline
    | by defining your `foreign` key column with an `onDelete`.
    |
    */
    'use_constraints' => false,

    'on_delete' => 'cascade',

    /*
    |--------------------------------------------------------------------------
    | Fake Nullables
    |--------------------------------------------------------------------------
    |
    | By default, Blueprint will set fake data even for nullable columns
    | within the generated model factories. However, you may disable
    | this behavior if you prefer to only set required columns
    | within your model factories.
    |
    */
    'fake_nullables' => true,

    /*
    |--------------------------------------------------------------------------
    | Use Guarded
    |--------------------------------------------------------------------------
    |
    | By default, Blueprint will set the `fillable` property within generated
    | models with the defined columns. These are set to provide a foundation
    | for mass assignment protection provided by Laravel. However, you may
    | configure Blueprint to instead set an empty `guarded` property to
    | generated "unguarded" models.
    |
    */
    'use_guarded' => false,

];

```

Thanks for any help!!

**Comment by jasonmccreary** [comment]
Believe some have reported this for Windows, but not Mac. I will try using Blueprint with a config file to see how I might be able to reproduce.

**Comment by gmgarrison** [comment]
If it's any help, I'm starting with this Laravel boilerplate: [https://github.com/jeremykenedy/laravel-auth](https://github.com/jeremykenedy/laravel-auth). From there, I think about all I've done is add Cashier. Let me know if I can provide anything else!

**Comment by jasonmccreary** [comment]
It's probably unrelated. But I will say Blueprint follows Laravel conventions and structure. So any customizations required by the "template" or "modules" package will need to be done manually, and as such likely diminish the value of Blueprint.

With that said, Blueprint should run without error for custom configurations.

**Comment by gmgarrison** [comment]
I assumed it would be unrelated but know that having as complete a picture as possible can come in handy in unexpected ways. To my (limited) understanding, the boilerplate follows Laravel conventions as most of it seems to come in the form of supplied middleware. If you end up spending any time poking around in it and come to a different conclusion, I'd appreciate hearing it!

**Comment by jasonmccreary** [comment]
Sorry, but I am unable to reproduce this error. I used your exact `draft.yaml` and `blueprint.php` config file.

It doesn't seem to be widespread, otherwise Blueprint would be completely unusable. So it has to be some kind of local setup I'm not expecting.

If you are so inclined, maybe you could dig into the code a bit to see what is missing.

A simple `dd()` of the values used in `TestGenerator.php` on line 76 would likely provide some clues.

**Comment by gmgarrison** [comment]
I just re-cloned that boilerplate repo, added Blueprint and it worked like a charm... I'll make a mental note to do Blueprint very early in my process and one day maybe I'll debug this and see what's happening. When/if that happens, I'll let you know. Thank you!!

**Comment by Ghosstk** [comment]
Hey! I have the same error.

Laravel Version: 7.15.0
PHP Version: 7.4.4
Blueprint Version: 1.14.0
Platform: Win10

draft.yml
```
models:
  Project:
    name: string:255
    payment_type: unsignedTinyInteger
    currency: string:10
    price: decimal:13,2
    start_at: timestamp nullable
    end_at: timestamp nullable
    relationships:
      belongsTo: User

controllers:
  Project:
    resource: api

seeders: Project
```

config:
```
<?php

return [
    'namespace' => 'App',
    'models_namespace' => 'Models',
    'controllers_namespace' => 'Http\\Controllers\\Api\\V1',
    'app_path' => 'app',
    'generate_phpdocs' => false,
    'use_constraints' => false,
    'on_delete' => 'cascade',
    'fake_nullables' => true,
    'use_guarded' => false
];

```
