### ISSUE TITLE
Support for composite indexes

### ISSUE THREAD

**Issue by DennisOng** [laravel-shift/blueprint#271]
Super useful package for quick prototyping. Glad to see this gaining traction and thanks for the effort you've put in.

### Synopsis:
There doesn't seem to be a way to define composite indexes (for migrations) in the draft model files

### Proposed Syntax:
```
models:
    Participation:
        project_id: bigInteger
        user_id: bigInteger
        name: string
        indexes:
          - unique: project_id, user_id
          - index: project_id, user_id
          - primary: project_id, user_id
```
### Expected Behavior:
```
Schema::table('participations', function (Blueprint $table) {
    $table->bigInteger('project_id');
    $table->bigInteger('user_id');
    $table->string('name');
    $table->unique(['project_id', 'user_id']);
    $table->index(['project_id', 'user_id']);
    $table->primary(['project_id', 'user_id']);
});
```

I think the main drawback is introducing the YAML array syntax, since as far as I know no other draft files in Blueprint uses that syntax so far. Otherwise could be quite a handy addition. Happy to take a stab at it if the syntax's approved, thanks!

**Comment by jasonmccreary** [comment]
@DennisOng in the past I have said this is an action to be performed after running Blueprint. I try to strike a delicate balance of what Blueprint is meant for (speed, convenience) against what might be faster to write in Laravel directly.

With that said, there is a `relationships` section recently added. So I am open to someone adding an `indexes`. See as you're probably interested in using this for [DrawSQL](https://drawsql.app/), I welcome your PR.

As far as the proposed syntax, you are correct that Blueprint does not use dashed syntax (again, speed). So you may simply use newlines.

Also, keying them by `unique`, `index`, `primary` may limit to only one of each _type_. Which is fine for `primary`, but not the others. So you'd have to check that.

For example:

```yaml
        indexes:
          unique: project_id, user_id
          unique: team_id, project_id
          index: project_id, user_id
          primary: project_id, user_id
```

**Comment by DennisOng** [comment]
Thanks @jasonmccreary. Makes sense, I can see how expecting Blueprint to do too much might dilute the focus of the tool. 

> Also, keying them by unique, index, primary may limit to only one of each type. Which is fine for primary, but not the others. So you'd have to check that.
Agree there might be an issue here especially for unique & index, hence my initial thought of having them listed as an array to allow for these duplicates. Wouldn't having duplicated keys here cause an issue for the YAML parser?

**Comment by jasonmccreary** [comment]
Yeah, I think they will overwrite. You can quickly test. So we'll likely need another syntax.

Part of me was thinking make it inline with the field, but that might feel awkward. For example:

```yaml
models:
    Participation:
        project_id: bigInteger unique:other,columns
        user_id: bigInteger
        name: string unique
        primary: project_id, user_id
```

You'd never be able to have a field named primary. Hence part of the awkwardness and why I have shied away from adding this _meta_ data.

Of course we could go back to supporting the _list_ YAML format for this specific thing. Or keying the indexes with something else, i.e. the key names. But that's equally as awkward to make the developer name them...

Anyway, open to thoughts. Feel free to just PR something and we can tweak it form there.

**Comment by DennisOng** [comment]
I agree with you there, that having them inline with the field would probably be too awkward.

Tricky one... will give it a go over the next few weeks and explore the different syntax while at it, cheers

**Comment by spaceemotion** [comment]
would be nice if you could specify full text indexes as well, which probably makes inline statements even weirder.

**Comment by TiiFuchs** [comment]
So this was added a while ago, but since the docs do not describe how to use it, it took me a while to stumble upon this issue. 

Maybe this should be added to the docs?

**Comment by elhagin** [comment]
How can this be used? I can't figure out how to build composite indices.

**Comment by rknmag** [comment]
For me following syntax helped
```
indexes:
  - unique:   user_name, company_name
```
Ref: https://github.com/laravel-shift/blueprint/issues/271

**Comment by niolson** [comment]
Is it possible to specify the name of an index?

This: 
```
  ProductTargetAttributeValue:
    product_id: id foreign
    target_attribute_id: id foreign
    value: string
    indexes:
      - unique: product_id, target_attribute_id
```
Generates this: 
```
        Schema::create('product_target_attribute_values', function (Blueprint $table) {
            $table->id();
            $table->foreignId('product_id')->constrained();
            $table->foreignId('target_attribute_id')->constrained();
            $table->string('value');
            $table->unique(['product_id', 'target_attribute_id']);
            $table->timestamps();
        });
```
Which generates an index name too long for MySQL. Is it possible to have it specify a name in the generated migration like this?

`            $table->unique(['product_id', 'target_attribute_id'], 'custom_index_name');`
