### ISSUE TITLE
Notification should generate assertSentTo

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#274]
- Laravel Version: 7.x
- PHP Version: 7.3
- Blueprint Version: 1.13.1
- Platform: All

### Issue:
Currently the `Notification` code generates the same assertions as a `Mailable`. Instead, it needs to generate [the appropriate assertions](https://laravel.com/docs/7.x/mocking#notification-fake) for a `Notification` (i.e. `assertSentTo`)

### draft.yaml:
```yaml
models:
  Post:
    title: string
    content: text
    author_id: id:user

controllers:
  Post:
    store:
      save: post
      send: ReviewNotification to:post.author with:post
```
