### ISSUE TITLE
FormRequestGenerator - Syntax to add additional rules; understand relationships and add 'exists'

### ISSUE THREAD

**Issue by nexxai** [laravel-shift/blueprint#28]
If you create a User model and a Messages model, if "user_id" is a field in the SendMessagesRequest  validator, it should be able to detect that "User" is an existing model, and require that the ID already exists in the "users" table.

Also, for the "validate:" line, there should be some kind of mark (I've used "(*)" in the example below, but it could be anything) that will tell the FormRequestGenerator to make the field unique.

For example:

```yaml
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp

controllers:
  Post:
    index:
      query: all
      render: post.index with:posts

    store:
      validate: title(*), content
```

Thoughts?
