### ISSUE TITLE
Boolean default:0 returns default() instead of default(0)

### ISSUE THREAD

**Issue by jyrkidn** [laravel-shift/blueprint#285]
- Laravel Version: 6.* and 7.*
- PHP Version: 7.4
- Blueprint Version: v1.15.0
- Platform: Linux

### Issue:

If I define a default value 0 for a boolean, in the migration it will show up as `$table->boolean('online')->default();`. Expected behavior would be: `$table->boolean('online')->default(0);`.

### draft.yaml:
```yaml
models:
  Category:
    title: string
    sort_order: integer default:10
  Page:
    title: string
    body: longtext
    category_id: id foreign:categories
    sort_order: integer default:10
    online: boolean default:0
```
