### ISSUE TITLE
Issue: Permission Denied

### ISSUE THREAD

**Issue by shahvirag** [laravel-shift/blueprint#289]
- Laravel Version: 7.x
- PHP Version: 7.4.7
- Blueprint Version: 1.15
- Platform: Windows

### Issue:
ErrorException 

file_put_contents(/Post.php): failed to open stream: Permission denied

### draft.yaml:
```yaml
models:
  Post:
    title: string:400
    content: longtext

controllers:
  Post:
    index:
      query: all
      render: post.index with:posts
```
