### ISSUE TITLE
API Resource Controller store_saves() requires assertCreated() to check 201 HTTP status

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#291]
- Laravel Version: 7.18.0
- PHP Version:  7.3.19
- Blueprint Version: https://github.com/laravel-shift/blueprint/commit/f289ca7a4f46369661706cba168e8ef83c689103
- Platform: Mac

### Issue:
As suggested on stream, the `assertOk()` should be an `assertCreated()` for `store_saves()` in the case of an API Resource Controller. In this context, a resource is returned, but Laravel knows to return a 201.

Output of `php artisan test`:

```sh
❯ a test

   PASS  Tests\Unit\ExampleTest
  ✓ basic test

   PASS  Tests\Feature\ExampleTest
  ✓ basic test

   FAIL  Tests\Feature\Http\Controllers\CertificateControllerTest
  ✓ index behaves as expected
  ✓ store uses form request validation
  ✕ store saves

  Tests:  1 failed, 4 passed, 11 pending

  Response status code [201] does not match expected 200 status code. Failed asserting that false is true.

  at tests/Feature/Http/Controllers/CertificateControllerTest.php:74
    70|             ->get();
    71|         $this->assertCount(1, $certificates);
    72|         $certificate = $certificates->first();
    73|
  > 74|         $response->assertOk();
    75|         $response->assertJsonStructure([]);
    76|     }
    77|
    78|
```

### draft.yaml:
```yaml
models:
  Certificate:
    name: string
    certificate_type_id: id
    reference: string
    document: string
    expiry_date: date
    remarks: nullable text
  CertificateType:
    name: string
    relationships:
      hasMany: Certificate

controllers:
  Certificate:
    resource: api
  CertificateType:
    resource: api
```
