### ISSUE TITLE
Ability to customize table name

### ISSUE THREAD

**Issue by misbahansori** [laravel-shift/blueprint#305]
The default convention is good. but when we want to use a non-English model name, we need to have an ability to specify the name of our table.

**Comment by jasonmccreary** [comment]
I think there's a growing need to have some kind of `meta` property for components. So I am open to this idea if you'd like to propose a syntax.

**Comment by enricobez** [comment]
This feature could be very useful, for example in italian language if I create a model for Utente (User) blueprint will create a table named Utentes that is not italian (Utenti is correct). So there's a way to avoid adding the 's' after the model name?
Thanks

**Comment by ajcastro** [comment]
how about we prefix it with something for example double underscores `__` or at `@` sign?

```yaml
User 
  @table: utenti 
  name: string
  email: string
```

```yaml
User 
  __table: utenti 
  name: string
  email: string
```
