### ISSUE TITLE
Migration filenames require sequence number

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#31]
Given the following `draft.yaml` which is modeled after a schema.org/Person:

```
models:
  Country:
    name: string
    isoAlpha2: string:2
    isoAlpha3: string:3
  ContactPoint:
    contactType: string
    email: string
    faxNumber: string
    telephone: string
  PostalAddress:
    country_id: id:country
    addressLocality: string
    addressRegion: string
    postalOfficeBoxNumber: string
    postalCode: string
    streetAddress: text
    contact_point_id: id:contact_point
  Person:
    additionalName: string
    address_id: id:postal_address
    familyName: string
    givenName: string
 ```

When running `blueprint:build`, it will yield migrations that do not have foreign key constraints for the related items.

Additionally: if the migrations would have had foreign key constraints, there would have been issues: the generated migrations all share the same timestamp in the filename, which means that they will be processed in alphabetical order, which will create a `people` table, before the `postal_addresses` table and therefore referencing a table that does not yet exists.

Example:
```sh
$ ls -1 database/migrations
...
2019_12_06_142421_create_contact_points_table.php
2019_12_06_142421_create_countries_table.php
2019_12_06_142421_create_people_table.php
2019_12_06_142421_create_postal_addresses_table.php
```

The order of the `models:` section was deliberate to make sure that the `blueprint:build` would generate in the correct order. However, since all of the generation occurred within the same second, the generated files fall back into alphabetical ordering.

So, implementing this would also require adding some kind of sequence numbering in the filename.
