### ISSUE TITLE
Option to generate routes using class/method tuple

### ISSUE THREAD

**Issue by spaceemotion** [laravel-shift/blueprint#321]
- Laravel Version: 7.21.0
- PHP Version: 7.4.3
- Blueprint Version: 1.16.0
- Platform: Linux (Ubuntu 20)

### Issue:

To improve type safety and against accidentally forgetting updating the routes file after renaming a controller class, I disabled the default namespace in the RouteServiceProvider.

However, this is not being picked up by blueprint. The api routes generated only reference the controller(s) via strings - not via class imports - so actually calling the routes fails and has to be corrected manually.

### draft.yaml:
```yaml
models:
  Person:
    id: string
controllers:
  Person:
    resource: api
```
