### ISSUE TITLE
relationship method is duplicated  if  using both  foreign  and  relationship instance  in  Record  Model

### ISSUE THREAD

**Issue by cs-abdulwahab** [laravel-shift/blueprint#325]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Blueprint Version: #.#.#
- Platform: Mac | Windows | Linux

### draft.yaml:
```yaml
models:
  User:
    username: string:100 unique
    password: string:400
    email: string:200 email
    phone: string:200
    relationships:
      hasMany: Meter
  Meter:
    code: string:100
    user_id: foreign
    relationships:
      hasMany: Record

  Record:
    current: integer default:-9999
    meter_id: foreign
    relationships:
      belongsTo: Meter

seeders: User,Meter,Record

```
