### ISSUE TITLE
Support custom pivot models

### ISSUE THREAD

**Issue by spaceemotion** [laravel-shift/blueprint#328]
### Synopsis:
Instead of the default A-B pivot relationship, I'd like to be able to add custom properties to the relationship. This should also generate a pivot model (class).

### Proposed Syntax:`
```yml
models:
  Person:
    name: string
    relationships:
      belongsToMany: Person:Contact

  Contact:
    pivot: true
    type: enum:friend,family,other
    timestamps
```
### Expected Behavior:
- Generates Person model
- Generates Contact pivot model
- Generates two migrations
