### ISSUE TITLE
Invalid namespace for JSON Resources when controller has namespace

### ISSUE THREAD

**Issue by spaceemotion** [laravel-shift/blueprint#329]
- Laravel Version: 7.21.0
- PHP Version: 7.4.3
- Blueprint Version: dev-master (1.16.0)
- Platform: Linux (Ubuntu 20)

### Issue:
When the controller has a custom namespace (e.g. `Api`), the imports for JSON resources is wrong. They get the same namespace added, while their actual location is just under "Resources":

```php
/**
 * @return \App\Http\Resources\Api\UserCollection
 */
```

folder structure:

```
- Http
  - Controllers
    - Api
      - UserController
  - Resources
    - UserCollection
```

### draft.yaml:
```yaml
models:
  User:
    id: integer
controllers:
  Api/User:
    resource: api
```
