### ISSUE TITLE
Idea: type hint faked in draft.yaml

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#33]
Here's an idea to 'type hint' the fakes in the `draft.yaml`

```yaml
models:
  Country:
    name: string fake:country
    isoAlpha2: string:2 fake:countryCode
    isoAlpha3: string:3 fake:countryISOAlpha3
  ContactPoint:
    contactType: string fake:randomElement['Procurement', 'Sales', 'Logistics', 'Planning', 'HR', 'Helpdesk', 'PR']
    email: string fake:email
    faxNumber: string fake:phoneNumber
    telephone: string fake:phoneNumber
  PostalAddress:
    country_id: id:country
    addressLocality: string fake:city
    addressRegion: string fake:state
    postalOfficeBoxNumber: string fake:randomNumber(4)
    postalCode: string fake:postcode
    streetAddress: text fake:streetAddress
    contact_point_id: id:contact_point
  Person:
    additionalName: string fake:firstName
    address_id: id:postal_address
    familyName: string fake:lastName
    givenName: string fake:firstName
```
