### ISSUE TITLE
Date model attributes should be cast to date

### ISSUE THREAD

**Issue by blackfyre** [laravel-shift/blueprint#335]
- Laravel Version: 7
- PHP Version: 7.4
- Blueprint Version: 1.15
- Platform: Mac | Windows | Linux

### Issue:
When defining date attributes on the model, I would expect that those attributes are cast to `date` type in the generated model files.

### draft.yaml:
```yaml
  Subscription:
    active_from: date nullable
    active_to: date nullable
```
