### ISSUE TITLE
Need to generate comments for some db columns

### ISSUE THREAD

**Issue by noorcs** [laravel-shift/blueprint#344]
### Synopsis:
While generating the migration using laravelshift-blueprint, I want to be able to generate comment for some columns as well.

### Proposed Syntax:
```
models:
  Profession:
    title: string:400
    description: string:400 nullable comment:'Some description for the profession'
```

### Expected Behavior:
```
Schema::create('professions', function (Blueprint $table) {
            $table->id();
            $table->string('title', 400);
            $table->string('description', 400)->nullable()->comment('Some description for the profession');
            $table->timestamps();
        });
```

### Current Output:
```
Schema::create('professions', function (Blueprint $table) {
            $table->id();
            $table->string('title', 400);
            $table->string('description', 400)->nullable();
            $table->timestamps();
        });
```
