### ISSUE TITLE
Model relationship definitions should add foreignKey argument

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#35]
Example input:
```yaml
  Person:
    additionalName: string
    award: string
    birthDate: date
    birthPlace_id: id:place
    callSign: string
    deathDate: date
    deathPlace_id: id:place
```

Should render:
```php
// \App\Person::class
// ...
    public function birthPlace()
    {
        return $this->belongsTo(\App\Place::class, 'birthPlace_id');
    }

    public function deathPlace()
    {
        return $this->belongsTo(\App\Place::class, 'deathPlace_id');
    }
```
