### ISSUE TITLE
Is there something I can add to the yaml or supporting yaml for seeds?

### ISSUE THREAD

**Issue by roni-estein** [laravel-shift/blueprint#360]
First of all thanks for this project, it's amazing!

I'd love it if there was a way I could add items to a yaml that I could use for migration seeding and testing.

For example, a list of Canadian provinces with abbreviations, or states in the USA. Items that you carry from project to project that need to be seeded, as well as new items that the database can't work without.

**Comment by jasonmccreary** [comment]
Interesting. Could you provide a sample syntax so I'm more clear on what you're trying to do? I think you're asking for something which generates seeders from data?

**Comment by roni-estein** [comment]
Hey sure, let me whip something together perhaps it might work or you can jump from it to a better alternative.

**Comment by roni-estein** [comment]
```
#Province:
#  abbr: string:2 primary
#  name_en: string:50
#  name_fr: string:50

#option 1 if we already know the fields from the models definition ignore field reference
#option 2 if thats not possible, list the fields for the seeder

seeders:
  ProvinceSeeder:
    #option 2 only
    fields: ['abbr', 'name_en', 'name_fr']
    - ['AB','Alberta', 'Alberta']
    - ['BC','British Columbia', 'Colombie-Britannique']
    - ['MB','Manitoba', 'Manitoba']
    - ['NB','New Brunswick', 'Nouveau-Brunswick']
    - ['NL','Newfoundland and Labrador', 'Terre-Neuve-et-Labrador']
    - ['NS','Nova Scotia', 'Nouvelle-Écosse']
    - ['NT','Northwest Territories', 'Territoires du Nord-Ouest']
    - ['NU','Nunavut', 'Nunavut']
    - ['ON','Ontario', 'Ontario']
    - ['PE','Prince Edward Island', 'Île-du-Prince-Édouard']
    - ['QC','Quebec', 'Québec']
    - ['SK','Saskatchewan', 'Saskatchewan']
    - ['YT','Yukon', 'Yukon']
```
