### ISSUE TITLE
Using app/Models

### ISSUE THREAD

**Issue by Wulfheart** [laravel-shift/blueprint#366]
### Synopsis:
With the release of Laravel 8 models are saved in ``app\Models`` if this folder exists. It would be nice for blueprint to adopt this behaviour.

### Proposed Syntax:
None

### Expected Behavior:
If the folder ``app\Models`` exists, the model reference will be this folder, e.g. ``app\Models\User::class``. If not, the reference will be under ``app``, e.g. ``app\User::class``.

I'd be happy to submit a PR for this.

**Comment by nathane** [comment]
Your PR is a welcomed addition, to update the default behavior.

---

### Blueprint supports custom namespaces.

- Set your custom model namespace in your config file.

1. Run `php artisan vendor:publish --tag=blueprint-config`

    > This will add a copy of the `blueprint.php` file in the `config` folder. Similar to the default Laravel configuration files.

2. Change the `'models_namespace'` options to `'app\Models'`

- Prefix the appropriate namespace relative to the model namespace in your draft file.

```yaml
models:
  app\Models\Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp

  app\Models\Comment:
    content: longtext
    published_at: nullable timestamp
```
