### ISSUE TITLE
Adding a User key to draft.yaml will cause overwrites user model with default model stub

### ISSUE THREAD

**Issue by roni-estein** [laravel-shift/blueprint#369]
### Synopsis:
When adding a user key to models section of draft.yaml, to add additional fields, or create relationships, the User class should use a specific stub user.stub to regenerate the mode instead of the base model. 

### Proposed Syntax:

```
models:
  User:
    relationships:
      belongsToMany: Foo
  Foo:
    bar: string
    relationships:
      belongsToMany: User
````

### Expected Behavior:

Overwrite prior models with base stub configuration, use an appropriate user.stub to overwrite the User model.
