### ISSUE TITLE
Idea: config/blueprint.php in which you can define output paths

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#37]
Some folks really dislike Laravel's default locations for generated output. A common occurrence is that folks might want to output models to `app/Models` instead of directly under `app/`. There are also others (myself included) that attempt to do some Domain separation of the business logic (not entirely DDD, but at least some sort of other structure).

Whilst tools like PhpStorm pack enough firepower to easily refactor the output, I still think it might be a good idea to at least configure some paths for the generator to output to? Love to read your take on this idea.

**Comment by DarkGhostHunter** [comment]
This could be at the `models` key level instead of a `blueprint.php`.

```yaml
models:
  config:
    model_path: app\Models
    migrations_path: database\migrations\example

  Post:
    config: 
      model_path: Publications
      migration_path: publications
```

That would output `.\app\Models\Publications\Post.php` with the `App\Models\Publications` namespace, and the same for the migration file. The problem is the `config` key, that someone could use in their column declaration, but that could be easily checked by using a safe `_config` if you have a key with the same name.

From there, the generator could create the table name from the key, but output to a different path, and use a different namespace

**Comment by robmpreston** [comment]
I did a rough version of this here, using the config idea above (but not allowing it on the individual model level) since we always use App\Models:

https://github.com/64robots/blueprint/commit/7d5d699b928c1674988eb9af8f82b217c48d4b9f

**Comment by robmpreston** [comment]
Realized one issue but basically works - will update later

**Comment by ManojKiranA** [comment]
I think its based on #14

**Comment by jasonmccreary** [comment]
I agree with @ManojKiranA, these two are pretty similar and will likely be implemented together. I'm just trying to think about ease of use and the developer experience.

The primary goal of Blueprint is rapid development. So I want a way that makes it quick and easy to specify these paths once.

**Comment by robmpreston** [comment]
> I agree with @ManojKiranA, these two are pretty similar and will likely be implemented together. I'm just trying to think about ease of use and the developer experience.
> 
> The primary goal of Blueprint is rapid development. So I want a way that makes it quick and easy to specify these paths once.

That's basically what I was going for, but when I think about for example controllers, it might be nice to be able to group them, like specify an API block and all controllers defined under that go into the API folder/namespace rather than having to define it under each.

**Comment by ManojKiranA** [comment]
I have Basically suggested the below syntax because of
```
models:
  Models/Blog/Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp
  Models/Blog/Comment:
    content: longtext
    commented_at: nullable timestamp
 Models/Admin/Tags:
    tag_name: string
```

By defining the Namespace of the each model in the name will be quite easy because we can define the Structure of the models placement in yaml itself.

Or if you are using the **global config** we need to **change every** time if we need to **generate the models in different namespace.**

Hope its clear now :relaxed:

ping @jasonmccreary  @robmpreston @DarkGhostHunter

**Comment by robmpreston** [comment]
I'd still want a way to define a base path, like `app\Models` that applies to all of them, then allow you to set individual paths on each one so like:

```yaml
models:
  config:
    path: app/Models
 Blog/Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp
 Blog/Comment:
    content: longtext
    commented_at: nullable timestamp
 Admin/Tags:
    tag_name: string
```
just IMO, would rather not have Models on each. Especially since in our case, we put everything in app/Models 95% of the time, so that extra level of configuration isn't that necessary for our use case.
