### ISSUE TITLE
Add configuration for generating class based routes

### ISSUE THREAD

**Issue by axit-joost** [laravel-shift/blueprint#377]
- Laravel Version: 8.6.0
- PHP Version: 7.3.21
- Blueprint Version: 1.19.1
- Platform: Mac

### Issue:

While I was updating my streamlined tests generator to support Laravel 8, as well as incorporating recent refactors done to Blueprint itself, I came across the issue that the registered API routes cause a `BindingResolutionException` in that it cannot reflect the controller, e.g. `"Target class [CertificateController] does not exist"`

To make this more concrete: currently Blueprint will register API routes like so:

In `routes/api.php`:
```php
Route::apiResource('certificate', 'CertificateController');
Route::apiResource('certificate-type', 'CertificateTypeController');
```
This works perfectly fine in L7, but in L8 it causes the exception:

```sh
   Illuminate\Contracts\Container\BindingResolutionException

  Target class [CertificateController] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:811
    807▕
    808▕         try {
    809▕             $reflector = new ReflectionClass($concrete);
    810▕         } catch (ReflectionException $e) {
  ➜ 811▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    812▕         }
    813▕
    814▕         // If the type is not instantiable, the developer is attempting to resolve
    815▕         // an abstract type such as an Interface or Abstract Class and there is

  1   [internal]:0
      Illuminate\Foundation\Console\RouteListCommand::Illuminate\Foundation\Console\{closure}(Object(Illuminate\Routing\Route))

      +13 vendor frames
  15  [internal]:0
      Illuminate\Foundation\Console\RouteListCommand::Illuminate\Foundation\Console\{closure}(Object(Illuminate\Routing\Route))
```

The [Laravel Documentation](https://laravel.com/docs/8.x/controllers#restful-partial-resource-routes) about registering API routes like this state the following form:

> Route::apiResource('photos', PhotoController::class);

If I adjust the code accordingly, referring to the `Class` (by either importing it or using the fully qualified class names) it works fine in both framework versions.

Like this:
```php
Route::apiResource('certificate', App\Http\Controllers\CertificateController::class);
Route::apiResource('certificate-type', App\Http\Controllers\CertificateTypeController::class);
```

### draft.yaml:
```yaml
models:
  Certificate:
    name: string
    certificate_type_id: id
    reference: string
    document: string
    expiry_date: date
    remarks: nullable text
  CertificateType:
    name: string
    relationships:
      hasMany: Certificate

controllers:
  Certificate:
    resource: api
  CertificateType:
    resource: api
```
