### ISSUE TITLE
PHP Fatal error:  Trait 'JMac\Testing\Traits\AdditionalAssertions' not found in ...

### ISSUE THREAD

**Issue by AngelinCalu** [laravel-shift/blueprint#378]
- Laravel Version: 8.6.0
- PHP Version: 7.4.6
- Blueprint Version: 1.19
- Platform: Windows 

### Issue:

`PHP Fatal error:  Trait 'JMac\Testing\Traits\AdditionalAssertions' not found in ...`

All of the controllers are referencing and using this trait which was not created:

```php
use JMac\Testing\Traits\AdditionalAssertions;

use AdditionalAssertions, //...  
```

### draft.yaml:
```yaml
Any new model with a resource controller will behave in the same manner. Example below:

controllers:
  Post:
    resource

```

Later Edit:

I've found out that I need to manually install this package. Not sure if this is the right way to proceed as it's nowhere mentioned in the docs

```
composer require --dev jasonmccreary/laravel-test-assertions
```
