### ISSUE TITLE
Add named relationship ability via draft.yaml

### ISSUE THREAD

**Issue by roni-estein** [laravel-shift/blueprint#383]
### Synopsis:
It would be great if we could name a relationship. In many relationships convention over anything makes sense, but there are lots of examples where they don't make sense, here is a quick thought example that I think could be automated. Right now, I just leave notes in the draft.yaml file and a task app but here is a quick thought experiment. 

Scenario: I want a "section" to have a behavior where actions can be disabled on it, if it's blocked by some other section(s). 

```
Section:
  invoice_id: id
  ... fields
  
  relationships:
    # todo: change this to a blockedBy relationship
    belongsToMany: Section, Another Model
```
### Proposed Syntax:

```
Section:
  invoice_id: id
  ... fields
  
  relationships:
    belongsToMany: blockedBy Section, AnotherModel 

# or 

    belongsToMany: Section blockedBy, AnotherModel

```

Thinking it through without human intelligence in play, I could make a belognsToMany relationship, between section and section. I could call this function blockedBy, I'd probably call the intermediary table with the name of the function and the model it represents, this is different then the normal two models plural alphabetical, but it's already different because it uses an named function. I'd name the table  "blocked_by_sections" that would have the following fields generated

```
$table->foreignId('section_id'); 
// given by the model of the original field since we defined this relationship on the "section" model
$table->foreignIdFor('blocked_by_id', Section::class);
// blocked_by_id since thats the snake case for the function name we gave it
// Section::class since that the model it represents in the relationship.
```

In the model, I'd add the belongs to many relationship with the proper function name, the named table and the named keys

```
  * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function blockedBy()
    {
        return $this->belongsToMany(\App\Models\Section::class, 'blocked_by_sections', 'blocked_by_id', 'section_id');
    }
```

I'm not sure if this would have any other farther reaching consequences, but I can't see it at the moment. Feedback appreciated. I'm not sure if I could produce this PR, but I'd be happy to try or pair with someone if this was wanted.

### Expected Behavior:

Produce "named" relationships from draft.yaml.
