### ISSUE TITLE
Invalid routes in Laravel 8

### ISSUE THREAD

**Issue by mattfletcher** [laravel-shift/blueprint#384]
- Laravel Version: 8.9.0
- PHP Version: 7.4.10
- Blueprint Version: 1.19.1
- Platform: Linux

### Issue: 
Running example draft.yaml creates invalid route in Laravel 8

Illuminate\Contracts\Container\BindingResolutionException
Target class [PostController] does not exist.

Since version 8, routes are defined using (e.g.) PostController::class rather than 'PostController'.

### draft.yaml:
```yaml
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp

controllers:
  Post:
    index:
      query: all
      render: post.index with:posts

    store:
      validate: title, content
      save: post
      send: ReviewNotification to:post.author with:post
      dispatch: SyncMedia with:post
      fire: NewPost with:post
      flash: post.title
      redirect: post.index

```
