### ISSUE TITLE
Models in in App\Models directory are not detected

### ISSUE THREAD

**Issue by ajcastro** [laravel-shift/blueprint#385]
- Laravel Version: 8.9.0
- PHP Version: 7.4.11
- Blueprint Version: v1.19.1
- Platform: Windows 

### Issue:
I installed the latest `laravel-shift/blueprint` and I have existing models in `App\Models` directory and when I ran `php artisan blueprint:new`, it didn't detect my models in `App\Models`

### draft.yaml:
N/A

**Comment by jasonmccreary** [comment]
Did you configure Blueprint to look in the `app/Models` folder?

**Comment by ajcastro** [comment]
@jasonmccreary yes I did try to put that configuration in `model_namespace`
```
    'models_namespace' => 'App\\Models',
    'controllers_namespace' => 'Http\\Controllers',
```

**Comment by ajcastro** [comment]
@jasonmccreary it also does not generate the models in `App\Models` directory, but it created the factories and migrations correctly

here is my `draft.yaml` file
```
models:
  Permission:
    name: string
    display_name: string nullable
    description: text nullable

  Role:
    name: string
    display_name: string nullable
    description: text nullable
```
