### ISSUE TITLE
SoftDeletes with Relationships

### ISSUE THREAD

**Issue by markusnissl** [laravel-shift/blueprint#39]
when SoftDeletes are enabled and relationships exist in the model, then `use SoftDeletes;` is also added for each function (invalid php code).

**Comment by jasonmccreary** [comment]
THanks. Do you have a sample _draft_ file or output as reference?

**Comment by markusnissl** [comment]
```
models:
  Post:
    name: string
    softDeletes
  Comment:
      post_id: unsignedBigInteger
      comment: text
      softDeletes
```

generates in Comment.php:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Comment extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'post_id',
        'comment',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'post_id' => 'integer',
    ];


    public function post()
    {
    use SoftDeletes;

        return $this->belongsTo(\App\Post::class);
    }
}

```
