### ISSUE TITLE
replacement {{ namespaceModel }} not correctly working in case for windows

### ISSUE THREAD

**Issue by amberlex78** [laravel-shift/blueprint#390]
- Laravel Version: 7.28.4
- PHP Version: 7.3.9
- Blueprint Version: 1.19.2
- Platform: Windows

### Issue:
 I have Windows 10 pro. When I use `php artisan blueprint:build` I get follow files: `database/factories/ArticleFactory.php` and `database/factories/CategoryFactory.php` with content:

```php
<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use Faker\Generator as Faker;
use {{ namespacedModel }};

$factory->define(Article::class, function (Faker $faker) {
    return [
        'category_id' => factory(\App\Models\Category::class),
        'title' => $faker->sentence(4),
        'slug' => $faker->slug,
        'content' => $faker->paragraphs(3, true),
    ];
});
```

```php
<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use Faker\Generator as Faker;
use {{ namespacedModel }};

$factory->define(Category::class, function (Faker $faker) {
    return [
        'parent_id' => factory(\App\Models\Category::class),
        'title' => $faker->sentence(4),
        'slug' => $faker->slug,
    ];
});
```

The problem is that in stubs files the line endings "\n"

In the file `vendor/laravel-shift/blueprint/src/Generators/FactoryGenerator.php` in `protected function populateStub` string 80 used code:
```php
$stub = str_replace('use Faker\Generator as Faker;'.PHP_EOL.'use {{ namespacedModel }};', $this->buildImports($model), $stub);
```
with `PHP_EOL`

For windows `PHP_EOL` is "\r\n" and no replacement occurs.

For test, if I replace `PHP_EOL` on `"\n"` in this case everything works.

Perhaps there are still sections of code where this does not work correctly for Windows

### draft.yaml:
```yaml
# PLEASE PASTE THE DRAFT FILE WHICH REPRODUCES THE ISSUE HERE...
models:
  Category:
    parent_id: id foreign:categories nullable
    title: string required
    slug: string required unique
    timestamps: true
    relationships:
      hasMany: Article

  Article:
    category_id: id foreign
    title: string required
    slug: string required unique
    content: mediumtext
    timestamps: true

seeders: Article, Category
```
