### ISSUE TITLE
Use `$casts` instead of `$dates` property

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#391]
### Synopsis:
The Model `$dates` property was deprecated in Laravel 8. In order to keep an eye to the future, Blueprint should register any dates as `$casts` instead - ideally with an inferred date type.

### Proposed Syntax:

```yaml
models:
  Post:
    published_at: datetime nullable
    reviewed_on: date nullable
```

### Expected Behavior:

```php
class Post extends Model
{
    protected $casts = [
        'published_at' => 'datetime',
        'reviewed_on' => 'date',
        // ...
    ];
}
```
