### ISSUE TITLE
Errors running blueprint on fresh Laravel + Sail + Jetstream setup

### ISSUE THREAD

**Issue by KimLangholz** [laravel-shift/blueprint#410]
- Laravel Version: 8.22.1
- PHP Version: 8.0.0
- Blueprint Version: 1.20.1
- Platform: Linux (WSL2)
- Sail: 1.1.0
- Jetstream: 2.1.0

### Issue:

When running 
``` 
sail artisan blueprint:build
```
I get the following error:

`[2021-01-13 13:33:15] local.ERROR: Call to a member function columns() on null {"exception":"[object] (Error(code: 0): Call to a member function columns() on null at /var/www/html/vendor/laravel-shift/blueprint/src/Generators/TestGenerator.php:251)
[stacktrace]
#0 /var/www/html/vendor/laravel-shift/blueprint/src/Generators/TestGenerator.php(89): Blueprint\\Generators\\TestGenerator->buildTestCases()
#1 /var/www/html/vendor/laravel-shift/blueprint/src/Generators/TestGenerator.php(64): Blueprint\\Generators\\TestGenerator->populateStub()
#2 /var/www/html/vendor/laravel-shift/blueprint/src/Blueprint.php(85): Blueprint\\Generators\\TestGenerator->output()
#3 /var/www/html/vendor/laravel-shift/blueprint/src/Builder.php(26): Blueprint\\Blueprint->generate()
#4 /var/www/html/vendor/laravel-shift/blueprint/src/Commands/BuildCommand.php(65): Blueprint\\Builder->execute()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Blueprint\\Commands\\BuildCommand->handle()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#11 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#13 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#15 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#18 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#19 {main}
"} `

It builds the controllers and models, but not the views/tests. 

When then trying to run the erase
```
sail artisan blueprint:erase
```
I get the following error:

`[2021-01-13 13:33:34] local.ERROR: File does not exist at path .blueprint. {"exception":"[object] (Illuminate\\Contracts\\Filesystem\\FileNotFoundException(code: 0): File does not exist at path .blueprint. at /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:57)
[stacktrace]
#0 /var/www/html/vendor/laravel-shift/blueprint/src/Commands/EraseCommand.php(47): Illuminate\\Filesystem\\Filesystem->get()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Blueprint\\Commands\\EraseCommand->handle()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#7 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#9 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#10 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#11 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#14 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#15 {main}
"} `

I've tried it on another fresh Laravel/Sail/Jetstream install as well with same result. 

### draft.yaml:
```
models:
  Category:
    category_id: id 
    category: string
    timestamps: false
  
  Role:
    role_id: id
    role: string
    timestamps: false
  
  Person:
    person_id: id
    profile_image_path: string nullable
    name: string
    is_female: boolean
    is_actor: boolean
    is_dead: boolean
    birthdate: datetime nullable
    deathdate: datetime nullable
    burial_place: string nullable
    nationality: string nullable
    city: string nullable
    country: string nullable
    education: string nullable
    short_intro: longtext nullable
    biography: longtext nullable
    birth_city: string nullable
    birth_country: string nullable
    timestamps: false
  
  Relation:
    relation_id: id
    person_id: id
    relation: string
    related_person_id: id foreign:person
    timestamps: false
  
  Starsign:
    starsign_id: id
    name: string
    description: longtext nullable
    from_date: datetime
    to_date: datetime
    timestamps: false
  
  Movie:
    movie_id: id
    title: string
    publishing_date: datetime nullable
    cover: string nullable
    category_id: id
    timestamp: false
  
  Characters:
    character_id: id
    name: string
    timestamp: false
  
  MovieCharacter:
    movie_character_id: id
    character_id: id
    movie_id: id
    role_part: string nullable
    picture: string nullable
    timestamp: false
  
  MovieProduction:
    movie_production_id: id
    person_id: id
    role_id: id
    movie_character_id: id
    timestamp: false
  
  TvSeries:
    tv_series_id: id
    title: string
    publishing_date: datetime nullable
    cover: string nullable
    category_id: id
    seasons: integer nullable
    timestamp: false

  TvSeriesEpisode:
    tv_series_episode_id: id
    tv_series_id: id
    episode_number: integer nullable
    title: string
    publishing_date: datetime nullable
    cover: string nullable
    season: integer nullable
    timestamp: false


  TvSeriesCharacters:
    tv_series_characters_id: id
    character_id: id
    tv_series_id: id
    picture: string nullable
    role_part: string nullable
    timestamp: false

  TvSeriesProduction:
    tv_series_production_id: id
    tv_series_episode_id: id
    person_id: id
    role_id: id
    tv_series_character_id: id
    timestamp: false

controllers:
  Movie:
    resource

  TvSeries:
    resource
  
  Episode:
    resource
  
  Character:
    resource
  
  Category:
    resource

  Role:
    resource

  Person:
    resource

  Relation:
    resource
  
```
Am I doing something wrong?
