### ISSUE TITLE
Generate single model/controller directly from CLI with props

### ISSUE THREAD

**Issue by Wulfheart** [laravel-shift/blueprint#412]
### Synopsis:
Sometime I don't know everything in advance and want to use blueprint to generate one model with everything that is provided by blueprint (migrations already filled in, model casts, etc.).

### Proposed Syntax:
``php artisan blueprint:model Post --attributes=title:string:400;content:longtext;published_at:nullable,timestamp``

### Expected Behavior:
This will result in a temporary draft file with the content:
````yaml
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp
````

Then the ``php artisan blueprint:build`` command is called and after this the previously generated file is deleted.

What do you think about it?
