### ISSUE TITLE
Decimal:5,5 error "undefined array key 1"

### ISSUE THREAD

**Issue by tanthammar** [laravel-shift/blueprint#413]
- Laravel Version: 8.22.1
- PHP Version: 8.0
- Blueprint Version: 1.20.2
- Platform: Mac

### Issue:
Trying to create this:
```php
$table->decimal('rate', 5, 5);
```
Error: "undefined array key 1"
![image](https://user-images.githubusercontent.com/21239634/104918291-d0520480-5994-11eb-90ca-838164d98f84.png)

### draft.yaml:
```yaml
models:
  Vat: {
    uuid: string nullable
    name: string
    rate: decimal:5,5
    country: json nullable
    user_id: id nullable foreign onDelete:null
    team_id: id foreign
    relations:
      hasMany: Bookon Product Service Rental OrderRow Account
  },
```

**Comment by jasonmccreary** [comment]
The correct syntax would be:

```yaml
rate: decimal:5.5
```

I didn't account for internationalization.

**Comment by tanthammar** [comment]
@jasonmccreary please reopen

Your suggestion rate:decimal:5.5 removes the error but the migration becomes a mess.

```yaml
  Vat: {
    uuid: uuid
    name: string
    rate: decimal:5.5
    country: json nullable
    user_id: id nullable foreign onDelete:null
    team_id: id foreign
    softDeletes
    relations:
      hasMany: Bookon Product Service Rental OrderRow Account
  },
```

Outputs:
```php
    public function up()
    {
        Schema::disableForeignKeyConstraints();

        Schema::create('vats', function (Blueprint $table) {
            $table->id();
            $table->softDeletes('uuid');
            $table->foreign('uuid')->references('uuid')->on('uuids')->onDelete('set null');
            $table->timestamps();
        });

        Schema::enableForeignKeyConstraints();
    }
``` 

Also confused, should there be a trailing `comma` on the end of each row or not?
The docs has no commas but if I omit it the migrations goes crazy.

Adding a comma to each row makes the migrations nice but then I can't add a `decimal` column because I get the initial error back.,
