### ISSUE TITLE
Error when generating relations 

### ISSUE THREAD

**Issue by tanthammar** [laravel-shift/blueprint#416]
- Laravel Version: 8.22.1
- PHP Version: 8.0
- Blueprint Version: 1.20.2
- Platform: Mac

### Issue:
I'm unable to get a grip on how to define the yaml file.
Following the docs does not generate the desired result.

# Relations

**Following the docs**
* gives error from the `hasMany` definition
```yaml
models:
  Vat:
    uuid: string nullable
    name: string
    rate: decimal
    country: json nullable
    user_id: id nullable foreign onDelete:null
    team_id: id foreign
    softDeletes
    relations:
      hasMany: Bookon, Product, Service, Rental, OrderRow, Account
```

```
   TypeError 

  Blueprint\Lexers\ModelLexer::buildColumn(): Argument #2 ($definition) must be of type string, array given, called in /Users/tina/Sites/jetstream/vendor/laravel-shift/blueprint/src/Lexers/ModelLexer.php on line 184

  at vendor/laravel-shift/blueprint/src/Lexers/ModelLexer.php:214
    210▕ 
    211▕         return $model;
    212▕     }
    213▕ 
  ➜ 214▕     private function buildColumn(string $name, string $definition)
    215▕     {
    216▕         $data_type = null;
    217▕         $modifiers = [];
    218▕ 

      +18 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

------------------------

**When wraping the model in `{}` AND ending the lines with `,` comma:**
* It generates relations
* **but** `softDeletes` becomes a `string` column, (in factories to)
```yaml
models:
  Vat: {
    uuid: string nullable,
    name: string,
    rate: decimal,
    country: json nullable,
    user_id: id nullable foreign onDelete:null,
    team_id: id foreign,
    softDeletes,
    relations:
      hasMany: Bookon Product Service Rental OrderRow Account,
  }
```
```php
        Schema::create('vats', function (Blueprint $table) {
            $table->id();
            $table->string('uuid')->nullable();
            $table->string('name');
            $table->decimal('rate');
            $table->json('country')->nullable();
            $table->foreignId('user_id')->nullable()->constrained()->onDelete('set null')->cascadeOnUpdate();
            $table->foreignId('team_id')->constrained()->cascadeOnDelete()->cascadeOnUpdate();
            $table->string('softDeletes,');
            $table->timestamps();
        });
```

**Comment by nathane** [comment]
Use the `softDeletes: true` YAML syntax if you’re using `{}`, see if that help.

**Comment by jasonmccreary** [comment]
Looks like you're reporting two issues.

The first normally is an issue because the model references do not exist. You can run `blueprint:trace` beforehand so they are registered (and therefore not null).

The second is a syntax error. As @nathane pointed out in another thread, Blueprint uses a yaml-esque syntax. In this case the trailing comma and wrapped parenthesis are likely causing the issue.

**Comment by tanthammar** [comment]
@jasonmccreary please reopen

* Removed `{}` 
* removed `softDeletes`
* added models related to the relationship
* trying to get the `yaml` correct :)

```yaml
models:
  Bookon:
    name: json
  Product:
    name: json
  Service:
    name: json
  Rental:
    name: json
  OrderRow:
    name: json
  Account:
    name: json
  Vat:
    uuid: string nullable
    name: string
    rate: decimal:5,5
    country: json nullable
    user_id: id nullable foreign onDelete:null onUpdate:cascade
    team_id: id foreign
    deleted_at: timestamp
    created_at: timestamp
    updated_at: timestamp
    relations:
      hasMany: Bookon, Product, Service, Rental, OrderRow, Account
```

Error:
```
  TypeError 

  Blueprint\Lexers\ModelLexer::buildColumn(): Argument #2 ($definition) must be of type string, array given, called in /Users/tina/Sites/jetstream/vendor/laravel-shift/blueprint/src/Lexers/ModelLexer.php on line 183

  at vendor/laravel-shift/blueprint/src/Lexers/ModelLexer.php:213
    209▕ 
    210▕         return $model;
    211▕     }
    212▕ 
  ➜ 213▕     private function buildColumn(string $name, string $definition)
    214▕     {
    215▕         $data_type = null;
    216▕         $modifiers = [];
    217▕ 

      +18 vendor frames 
```
