### ISSUE TITLE
Failure with models ending with the letter s.

### ISSUE THREAD

**Issue by CristianH033** [laravel-shift/blueprint#424]
- Laravel Version: 8.25.0
- PHP Version: 7.4.3
- Blueprint Version: 1.21.0
- Platform: Linux

### Issue:
When trying to create a model ending in the letter s, test creation fails.
In this example I use the word "Pais" (country in Spanish).

### draft.yaml:
```yaml
models:
  Pais:
    nombre: string

controllers:
  Pais:
    resource: api

seeders: Pais
```
When I run the php artisan blueprint:build command I get this error:
![image](https://user-images.githubusercontent.com/4079493/106194690-284eef00-617d-11eb-8ea1-74c9b5859644.png)

Then I change the draft.yaml file and remove the letter s at the end of the word.

### draft.yaml:
```yaml
models:
  Pai:
    nombre: string

controllers:
  Pai:
    resource: api

seeders: Pai
```
And again I run the php artisan blueprint:build command:
![image](https://user-images.githubusercontent.com/4079493/106195144-bfb44200-617d-11eb-9e79-c20f32cd6c38.png)

And this time the command works correctly.

I have already tried it with other words and the problem seems to be when the singular word ends in s.

Thanks for the attention and I love this package, it saves a lot of development time.
