### ISSUE TITLE
Nested Resources 

### ISSUE THREAD

**Issue by natecorkish** [laravel-shift/blueprint#430]
### Synopsis:

The ability to generate nested resources for other models/controllers. For example:

A job can have many comments, but a course could also have many comments, and they would use a Comment model, with a commentable morph (which we can do already), now to comments on a job, to do this Laravel's way you can do:

web.php

```
Route::resource('job.comment', JobCommentController::class);
```

JobCommentController.php

```
class JobCommentController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Job $job
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function store(CommentRequest $request, Job $job, Comment $comment)
    {
        $comment = $job->comments()->create(array_merge([
            'owner_type' => 'user',
            'owner_id' => Auth::user()->id
        ], $request->validated()));

        return Redirect::back()->withSuccess('You have added a comment to this job');
    }
}
```

Currently we don't have a way to do this. Would this be something you're open to?

### Proposed Syntax:
```
    # Job Comment Controller
    Job/JobComment:
        resource: store, destroy
        model: job
        nested: comment
        validation: comment/comment
```

So, the `model` is the resource model It is nested for, and `nested` is the model it uses to store/delete data, the `validation` is the file It generate for validation. Because the comment is used for multiple resources, it doesn't make sense to add that under the `Requests/Job/ folder`

**Comment by faustbrian** [comment]
Would this syntax be less clutter? We could still derive the `JobCommentController` name and we can treat each segment as a model without the user having to specify the `model` and `nested` properties since the `/` should already indicate the nesting.

```yml
Job/Comment:
  resource: store, destroy
  validation: comment/comment
```

**Comment by jasonmccreary** [comment]
I'm not following this very closely. However, I agree we could infer some things by default. But we should allow the proposed syntax in the event they are not following conventions.

Also, the `model`, `nested`, and `validation` should be `meta` properties. Only `resource` and `meta` should be top level.

**Comment by faustbrian** [comment]
@jasonmccreary I started to play a bit with this in https://github.com/faustbrian/blueprint/commit/7bfec8bb827218229eaedd3b38d2b0244bdd5f3a and it isn't that invasive of a change except for the statement generation. Most statement classes work based on the name of the controller so for a nested controller we would need to internally change the return value of `Controller::name` and `Controller::prefix` to match the name of the last segment or a lot of places will break in odd ways.

For example variables need to be named `$comment` instead of `$jobComment` but all of this is so deeply integrated into the system that it seems to be a rather big change. I think one way to approach this is to create `ResourceControllerGenerator` and `NestedResourceControllerGenerator` classes and then `ControllerGenerator` invokes either of them based on the name of the controller. This wouldn't cause any changes on the surface and allow each generator to build up strings as they need to since there are a fair few differences between a resource and nested resource controller.

**Comment by jasonmccreary** [comment]
This landed via #725 — nested resource controllers are supported through `meta.parent`:

```yaml
models:
  Post:
    title: string
    body: text
    relationships:
      hasMany: comment
  Comment:
    body: text
    relationships:
      belongsTo: post

controllers:
  Comment:
    resource: api
    meta:
      parent: post
```

Generates:

```php
Route::apiResource('posts/{post}/comments', CommentController::class);
```

```php
public function store(CommentStoreRequest $request, Post $post): CommentResource
{
    $comment = $post->comments()->create($request->validated());

    return new CommentResource($comment);
}
```

The parent model is injected into every resource method, and statements resolve through the relationship instead of the model directly. While this may not fully align with the spec of this issue, given how long both sat, I'm closing as "good enough".
