### ISSUE TITLE
Controller not importing App/Models/Model from traced models

### ISSUE THREAD

**Issue by marsd** [laravel-shift/blueprint#436]
I have a set of existing Models in `App/Models` namespace that have been successfully traced. However, the generated Controller does not import the correct namespace. 

Am I missing something in draft.yaml to reference the correct Model?

.blueprint
```
λ php artisan blueprint:new
Traced 44 models
//
models:
...
    Models\Collection: { collection_id: 'integer nullable', uuid: 'string default:public.gen_random_uuid()', workflow_step_1: 'string nullable', workflow_step_2: 'string nullable', workflow_step_3: 'string nullable', submitter: 'string nullable', template_item_id: 'string nullable', logo_bitstream_id: 'string nullable', admin: 'string nullable' }
...
```

draft.yaml
```yaml
models:
  # ...
controllers:
  Community:
    index:
      query: all:communities
      render: community.index with:communities
```

config
```php
'models_namespace' => 'Models',
// and
'generate_fqcn_route' => true,
```

CommunityController.php
```php
<?php

namespace App\Http\Controllers;

use App\Community;
use Illuminate\Http\Request;

// ...
```
