### ISSUE TITLE
Default values for boolean and integer come out as strings in migrations,

### ISSUE THREAD

**Issue by roni-estein** [laravel-shift/blueprint#440]
- Laravel Version: 8.31.0
- PHP Version: 7.4.14
- Blueprint Version: dev-master
- Platform: Mac | Windows | Linux

### Issue:
default for boolean and integer come out as strings, should be numeric or boolean per docs.

### draft.yaml:
```yaml
models:
  AppointmentQuestions:
    appointment_type_id: id foreign
    question_type_id: id foreign
    order: integer default:1
    required: bool default:true
    placeholder: string nullable
    question: string
    hint: string nullable
```

```php
  Schema::create('appointment_questions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('appointment_type_id')->constrained()->cascadeOnDelete()->cascadeOnUpdate();
            $table->foreignId('question_type_id')->constrained()->cascadeOnDelete()->cascadeOnUpdate();
            $table->integer('order')->default('1');
            $table->string('required')->default('true');
            $table->string('placeholder')->nullable();
            $table->string('question');
            $table->string('hint')->nullable();
            $table->timestamps();
        });
```
