### ISSUE TITLE
View creation

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#450]
- Laravel Version: 8.33.1
- PHP Version: 7.4.3
- Blueprint Version: 1.23 
- Platform: Linux

Bug or I don't understand the doc

https://laracasts.com/discuss/channels/general-discussion/laravel-blueprint-view-creation

### Issue:
The blade generated view is blank.
```
{{--
    @extends('layouts.app')

    @section('content')
        post.index1 template
    @endsection
--}}
```

### draft.yaml:
```yaml
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp

controllers:
  Post:
    index:
      query: all
      render: post.index with:posts
```
