### ISSUE TITLE
Bug? in show function.

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#451]
Laravel Version: 8.33.1
    PHP Version: 7.4.3
    Blueprint Version: 1.23
    Platform: Linux

### Issue:
Generated
```
    public function show(Request $request, Post $post)
    {
        return view('post.show', compact('post'));
    }
```
Expected
```
    public function show( $id ){
        $post = Post::where('id',$id)->first();
        return view('post.show',compact('post'));
    }
```
Source concerned : ControllerGenerator / buildMethods

Proposed solution
in ControllerGenerator / methods loop, add
$body = "        $variable = $context::where('id',\$id)->first();".PHP_EOL;

PS : route (web.php) is also concerned, but I don't the workaround till now

### draft.yaml:
```yaml
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp useCurrent

controllers:
  Post:
    index:PS : route (web.ph
      query: all
      render: post.index with:posts
    create:
      render: post.create
    store:
      validate: post
      save: post
      flash: post.id
      redirect: post.index
    show:
      render: post.show with:post
```
