### ISSUE TITLE
Wrong routes order

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#453]
Laravel Version: 8.33.1
PHP Version: 7.4.3
Blueprint Version: 1.23
Platform: Linux

### Issue:
Let's imagine we want 2 index views (index & index2 - 2 choices to be decided by users for instance).
The generated routes (web.php) do not work
```
Route::resource('post', App\Http\Controllers\PostController::class);
Route::get('post/index2', [App\Http\Controllers\PostController::class, 'index2']);
```
It should be
```
Route::get('post/index2', [App\Http\Controllers\PostController::class, 'index2']);
Route::resource('post', App\Http\Controllers\PostController::class);
```

### draft.yaml:
```yaml
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp useCurrent

controllers:
  Post:
    index2:
      query: all
      render: post.index2 with:posts
    index:
      query: all
      render: post.index with:posts
```
### propose solution(s):
file : RouteGenerator.php
1) Easiest - resource routes at the end
#453            $routes .= $this->buildRouteLine($className, $slug, $method);
#453            $routes .= PHP_EOL;
            $routes = $this->buildRouteLine($className, $slug, $method) . PHP_EOL . $routes;		#453

2) Routes in the 'same' order of draft.yaml
not useful ?
