### ISSUE TITLE
Wrong Docblocks for controller method

### ISSUE THREAD

**Issue by uyab** [laravel-shift/blueprint#459]
- Laravel Version: 8.35.1
- PHP Version: 8.0.3
- Blueprint Version: 1.32.1
- Platform: Mac

### Issue:

![image](https://user-images.githubusercontent.com/149716/113132198-52d62a80-9248-11eb-9d10-ab3d66b12b8e.png)

### draft.yaml:
```yaml
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp

controllers:
  Post:
    resource
```
