### ISSUE TITLE
Nullable not written in validation rules

### ISSUE THREAD

**Issue by sr57** [laravel-shift/blueprint#462]
Laravel Version: 8.33.1
PHP Version: 7.4.3
Blueprint Version: 1.23
Platform: Linu

### Issue:
Code generated in TagStoreRequest.php
```
 'tag_id' => ['integer'],
```
expected 'tag_id' => ['integer'],
```
 'tag_id' => ['integer','nullable'],
```

### draft.yaml:
```
models:
  Tag:
    tag_id: biginteger nullable             # parent
    name: string:32
      
controllers:
  Tag:
    resource: web
```
