### ISSUE TITLE
 Call to a member function columns() on null

### ISSUE THREAD

**Issue by WhalesHaveAccents** [laravel-shift/blueprint#464]
- Laravel Version: 8.12
- PHP Version: 8.0.3
- Blueprint Version: 1.23
- Platform: Mac 

- Issue: 
After running php artisan blueprint:build I get the following error: 
Call to a member function columns() on null
```php

at vendor/laravel-shift/blueprint/src/Generators/TestGenerator.php:251

$setup['data'][] = $faker;
                                 $request_data[$data] = '$' . $variable_name;
                                } else {
                                 foreach ($local_model->columns() as $local_column) {
                                        if ($local_column->name() === 'id') {
                                            continue;
                                        }
```
I found a solution by googling it, but not sure if it's correct or not??? can someone confirm it's the right approach or an error in my yaml file?

```php

 $setup['data'][] = $faker;
                                $request_data[$data] = '$' . $variable_name;
                            } else if (!is_null($local_model)) {
                                foreach ($local_model->columns() as $local_column) {
                                    if ($local_column->name() === 'id') {
                                        continue;
                                    }
 ```
### draft.yaml:
```yaml

```

**Comment by nathane** [comment]
A patch was released to address this, run `composer update` to update Blueprint.

**Comment by WhalesHaveAccents** [comment]
I'd have thought it would come down when I ran `composer require --dev laravel-shift/blueprint` this morning when I installed it on a fresh project, not have to do an update as well??

I was aware of it the other day, and fixed it by the method above, but been testing other stuff, so I left it until I needed to reinstall it on another project to see if it had been picked up...

Guess folks have to run 
```
composer require --dev laravel-shift/blueprint
composer update
```

**Comment by jasonmccreary** [comment]
@WhalesHaveAccents, did running `composer update` solve the issue?

**Comment by WhalesHaveAccents** [comment]
@jasonmccreary Nope!

Steps I have done....
 - Installed package `composer require --dev laravel-shift/blueprint`
- did my own fix, it worked
- ran `composer update`
- thought it had fixed it, went out....
- came back saw your reply
- removed the package completely to test make sure the composer update worked...
- ran `composer require --dev laravel-shift/blueprint` V1.23
- ran `composer update`

Same error as above....

It works when I add `else if (!is_null($local_model))` at line 250 but i'm unsure if this is correct

**Comment by jasonmccreary** [comment]
@WhalesHaveAccents okay. I'll have to dig into it as I'm not sure why `$local_model` would be `null` at this point.

Can you supply a relevant `draft.yaml` file. Ideally something a bit more condensed which recreates the issue.

**Comment by WhalesHaveAccents** [comment]
This is my full file I try to run..
```yaml
models:
    FacilityType:
            facilty_name: string:100
            facility_icon: text
            status: enum:active,inactive,deleted default:active
            softDeletes
    #Partner Type
    PartnerType:
            partner_type: string:100
            subsctiption_required: boolean default:0
            onboarding_required: boolean default:0
            status: enum:active,inactive,deleted default:active
            softDeletes
    #Partner can be multiple Partner types, belongs to team user can be assigned to a team to maange partner page
    Partner:
            user_id: id foreign:users
            partner_type_id: id foreign:partner_types
            partner_name: string:100
            slug: string:100
            address: string:100
            street: string:100
            town: string:100
            county: string:100
            region: string:100
            postcode: string:100
            country: string:100
            latitude: string:100
            longtitude: string:100
            contact_name: string:100
            contact_surname: string:100
            contact_email: string:100 unique
            contact_number: bigint:20
            company_website: string:100 nullable
            company_description: text
            environmental_agency_fishery_licence: enum:yes,no default:no
            public_liability_insurance: enum:yes,no default:no
            subscription_status: enum:active,inactive,free applicable default:inactive
            subscription_type: enum:official,premium,free applicable default:free
            logo_path: text
            background_path: text
            status: enum:active,inactive,deleted default:inactive
            relationships:
                hasMany: partner_types,partner_facility_types
            softDeletes
    #Default list of Fish Species 
    SpeicesType:
            species_name: string:100
            status: enum:active,inactive,deleted default:active
            softDeletes
    #List of Water Types IE Pond, lake, River 
    WaterType:
            water_type: string:100 
            status: enum:active,inactive,deleted default:active
            softDeletes
    #Each Water Belongs to a single Partner
    PartnerWater:
            partner_id: id foreign:partner
            water_type_id: id foreign:watertype
            water_name: string:100
            is_bookable: boolean default:0
            number_of_pegs: bigint:20
            status: enum:active,inactive,deleted default:inactive
            softDeletes
    #Each Partner can create thier own Peg types, IE Single Peg, Double Peg, Tripple Peg
    PartnerPegType:
            partner_id: id foreign:partner
            peg_type: string:100
            status: enum:active,inactive,deleted default:inactive
            softDeletes
    #Each Partners Peg on a Water, Belongs to a Partner Water and Has Many Pegs IE some waters might have 10 signle pegs or 20 mixed pegs types
    PartnerWaterPegs:
            water_id: id foreign:partnerwater
            partner_peg_type: id foreign:partnerpegtype
            peg_number: bigint:20
            status: enum:active,inactive,deleted default:inactive
            relationships:
                hasMany: partnerpegtype
            softDeletes
    PartnerFacilityType:
            partner_id: id foreign:partners
            facility_id: id foreign:facility_types
    #Pivot Table Each Partner Water can have several Fish Species Living in it
    PartnerWaterSpecies:
            water_id: id foreign:partnerwaters
            species_id: id foreign:speciestype
    #Partners Syndicate belongs to a partner
    PartnerSyndicate:
            partner_id: id foreign:partner
            syndicate_name: string:100
            yearly_fee: decimal:8,2
            deposit: decimal:8,2
            total_seats: bigint:20
            status: enum:active,inactive,deleted default:active
            softDeletes
    #Partner Syndicate list is a list of users that belong to a syndicate
    PartnerSyndicateList:
            partner_id: id foreign:partner
            syndicate_id: id foreign:partnersyndicate
            user_id: id foreign:users
            deposit_paid: enum:yes,no
            status: enum:active,inactive,deleted default:active
            softDeletes
    #Partner Match belongs to a partner and can be held on or off their own water.
    PartnerMatches:
            partner_id: id foreign:partner
            water_id: id foreign:partnerwaters
            match_name: string:100
            match_info: text nullable
            match_fee: decimal:8,2 nullable
            match_date: date nullable
            match_start_time: string:50 nullable
            match_finish_time: string:50 nullable
            status: enum:active,inactive,deleted default:active
            softDeletes
    #Match Result belongs to a Partners Match
    PartnerMatchResult:
            partner_match_id: id foreign:partnermatches
            first_place: string:100
            second_place: string:100
            third_place: string:100
            first_weight: string:100 nullable
            second_weight: string:100 nullable
            third_weight: string:100 nullable
            full_results: text nullable
            status: enum:active,inactive,deleted default:active
            softDeletes
    #Partner Promotion Belongs to a Partner
    PartnerPromotions:
            partner_id: id foreign:partner
            title: string:100
            content: text nullable
            image: text nullable
            start_date: date nullable
            end_date: date nullable
            status: enum:active,inactive,deleted default:active
            softDeletes
controllers:
    #Partner Type
    PartnerType:
        resource: web
    FacilityType:
        resource: web
    #Partner 
    Partner:
        index:
                query: where:status order:partner_name 
                render: partner.index with:partners
        create:
                render: partner.create 
        store:
                validate: user_id,partner_type_id,partner_name,address,town,county,region,postcode,contact_name,contact_surname,contact_email,contact_number
                save: partner
                flash: partner.partner_name
                redirect: dashboard
        show:
                query: where:slug order:partner_name where:status
                render: partner.show with:partners,partnerwater,partnerpegtype,partnerwaterpegs,partnerwaterspecies,partnersyndicate,partnermatches,partnermatchresults,partnerpromotions
        edit:
                render: partner.edit
        update:
                validate: user_id,partner_type_id,partner_name,address,town,county,region,postcode,contact_name,contact_surname,contact_email,contact_number
                update: partner
                flash: partner.partner_name
                redirect: dashboard
        destroy:
                delete: partner
                redirect: dashboard
    #Default list of Fish Species 
    SpeicesType:
        resource: web
    #List of Water Types IE Pond, lake, River 
    WaterType:
        resource: web
    #Each Water Belongs to a single Partner
    PartnerWater:
        resource: web
    #Each Partner can create thier own Peg types, IE Single Peg, Double Peg, Tripple Peg
    PartnerPegType:
        resource: web
    #Each Partners Peg on a Water, Belongs to a Partner Water and Has Many Pegs IE some waters might have 10 signle pegs or 20 mixed pegs types
    PartnerWaterPegs:
        resource: web
    #Pivot Table Each Partner Water can have several Fish Species Living in it
    PartnerWaterSpecies:
        resource: web
    #Partners Syndicate belongs to a partner
    partnerSyndicate:
        resource: web
    #Partner Syndicate list is a list of users that belong to a syndicate
    partnerSyndicateList:
        resource: web
    #Partner Match belongs to a partner and can be held on or off their own water.
    PartnerMatches:
        resource: web
    #Match Result belongs to a Partners Match
    PartnerMatchResult:
        resource: web
    #Partner Promotion Belongs to a Partner
    PartnerPromotions:
        resource: web
```
