### ISSUE TITLE
Many to Many Polymorphic

### ISSUE THREAD

**Issue by adgower** [laravel-shift/blueprint#482]
### Synopsis:
I would like to be able to dynamic generate many to many polymorphic relationships using blueprint. For example: Posts and Images have multiple Tags.

### Proposed Syntax:
```
models:
  Post:
    relationships:
    morphedToMany: Taggable

  Image:
    relationships:
    morphedToMany: Taggable

  Tag:
    relationships:
    morphedByMany: Taggable
```

### Expected Behavior:
Generates
- Models: Post, Image, Tag
- with relationships
- tables: posts, images, tags, taggables
