### ISSUE TITLE
Duplicate key "hasMany" detected at line ..

### ISSUE THREAD

**Issue by HRR1337** [laravel-shift/blueprint#492]
- Laravel Version: 8.52.0
- PHP Version: 7.4.19
- Blueprint Version: 1.24.1
- Platform: Windows

### Issue:

Duplicate key "hasMany" detected at line xx when I have multiple hasMany rows.

p.s. the `php artisan blueprint:trace` before `php artisan blueprint:build` is not fixxing the issue here.

### draft.yaml:
```yaml
models:
  Company:
    name: string
    stripe: string
    taxid: string
    relationships:
      hasMany: Location
      hasMany: Partner
    softDeletes

  Location:
    name: string unique
    address: string
    zipcode: string
    placename: string
    phone: string
    email: string
    relationships:
      belongsTo: Company
      hasMany: Product
    softDeletes

  Partner:
    name: string
    email: string
    percentage: tinyint # 0 - 255 
    status: enum:enabled,disabled
    relationships:
      belongsTo: Company
    softDeletes
```

It wont give a error message when you change on of the relationships thats the same with an capital. But this feels hacky, and not sure if it gives issues in the feature. 

### draft.yaml:
```yaml
models:
  Company:
    name: string
    stripe: string
    taxid: string
    relationships:
      hasMany: Location
      HasMany: Partner
    softDeletes

```

**Comment by jasonmccreary** [comment]
You separate multiple relationships of the same types with commas. So:

```yaml
models:
  Company:
    name: string
    stripe: string
    taxid: string
    relationships:
      hasMany: Location,  Partner
    softDeletes
```
