### ISSUE TITLE
Can't make relationship with user

### ISSUE THREAD

**Issue by spham** [laravel-shift/blueprint#510]
Hi
maybe it not a bug

but i cant make a relationship with a User

Cannot declare class CreateUsersTable, because the name is already in use

```
models:
  Project:
    name: string
    description: string
    relationships:
      belongsToMany: User
  User:
    relationships:
      hasMany: Project
```
