### ISSUE TITLE
Dispatch Statement - Undefined array key 1

### ISSUE THREAD

**Issue by dmason30** [laravel-shift/blueprint#549]
- Laravel Version: 9.x
- PHP Version: 8.x
- Blueprint Version: 2.3
- Platform: Mac

### Issue:
On my pest php extension @tanthammar raised this issue (https://github.com/fidum/laravel-blueprint-pestphp-addon/issues/33) about a exception that occurs when generating a dispatch statement when the variables used have no context. 

I ran the same yaml on pure blueprint without my extension and encountered the same error (see below). This affects `dispatch`, `fire`, `notify` and `send` statements.

Questions to be asked are:

- Should we support blueprint yaml configurations we we have no context for the variables being generated?
- Is the below yaml valid as it leads to generated tests that fail as it does not setup the `$event` variable?

### draft.yaml:
```yaml
controllers:
    Report:
      invokable:
        dispatch: GenerateReport with:event
        fire: ExportReport with:event
        render: report
    Transaction:
      __invoke:
        notify: auth.user ReportGenerated with:event
        send: SendReport with:event
        render: transaction
```

### Fix
The fix is to change this line for each statement in `TestGenerator` from:

```php
if (Str::studly(Str::singular($data)) === $this->context) {
```

To also check if the `$data` contains a `.` to treat the variable as is.

```php
if (Str::studly(Str::singular($data)) === $this->context || ! Str::contains($data, '.')) {
```

I applied this fix in my extension which prevents the below error here https://github.com/fidum/laravel-blueprint-pestphp-addon/pull/34/files.

### Issue reported on my repo
> https://github.com/fidum/laravel-blueprint-pestphp-addon/issues/33
> ```yaml
> Report:
>     __invoke:
>       dispatch: GenerateReport with:event
>       notify: auth.user ReportGenerated with:report
>       render: report
> ```
> 
> Error:
> 
> ```
>   Undefined array key 1
> 
>   at vendor/fidum/laravel-blueprint-pestphp-addon/src/Builders/Statements/DispatchStatementBuilder.php:32
>      28▕                 if (Str::studly(Str::singular($data)) === $this->context) {
>      29▕                     $variables[] .= '$'.$data;
>      30▕                     $conditions[] .= sprintf('$job->%s->is($%s)', $data, $data);
>      31▕                 } else {
>   ➜  32▕                     [$model, $property] = explode('.', $data);
>      33▕                     $variables[] .= '$'.$model;
>      34▕                     $conditions[] .= sprintf('$job->%s == $%s', $property ?: $model,
>      35▕                         str_replace('.', '->', $data()));
>      36▕                 }
> 
>       +22 vendor frames 
>   23  artisan:37
>       Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> ```
