### ISSUE TITLE
[BUG] Adding Softdeletes

### ISSUE THREAD

**Issue by ManojKiranA** [laravel-shift/blueprint#55]
1. Adding `softDeletes` in yaml adds `'softDeletes' => $faker->word,` inside factory

Steps to reproduce
```
models:
  Post:
    title: string:400
    content: longtext
    published_at: nullable timestamp
    softDeletes: true

```
