### ISSUE TITLE
Missing import on single-action controller

### ISSUE THREAD

**Issue by spekulatius** [laravel-shift/blueprint#583]
- Laravel Version: v9.43.0
- PHP Version: PHP 8.1.13
- Blueprint Version: v2.4.0
- Platform: ArchLinux

### Issue:

It seems the generated controller test misses the `use` for the related model, if only a `show`-action is defined on the controller.

### draft.yaml:
```yaml
models:
  Entry:
    slug: string:400
    title: string:400
    intro: longtext

controllers:
  Entry:
    show:
      render: entry.show with:entry
```

Here the generated ControllerTest with the expected diff:

```diff
<?php

namespace Tests\Feature\Http\Controllers;

+use App\Models\Entry;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\EntryController
 */
class EntryControllerTest extends TestCase
{
    /**
     * @test
     */
    public function show_displays_view()
    {
        $entry = Entry::factory()->create();

        $response = $this->get(route('entry.show', $entry));

        $response->assertOk();
        $response->assertViewIs('entry.show');
        $response->assertViewHas('entry');
    }
}

```
