### ISSUE TITLE
RememberToken has empty faker stmt in UserControllerTest

### ISSUE THREAD

**Issue by Konafets** [laravel-shift/blueprint#587]
- Laravel Version: 9.38.0
- PHP Version: 8.1.12
- Blueprint Version: 2.4
- Platform: Mac

### Issue:

The `remember_token` has an unfinished faker statement in the generated `UserControllerTest::store_saves_and_redirects`:

```php
    /**
     * @test
     */
    public function store_saves_and_redirects(): void
    {
        $name = $this->faker->name;
        $email = $this->faker->safeEmail;
        $password = $this->faker->password;
        $remember_token = $this->faker->;
        // Error on the line above ...
```

### draft.yaml:
```yaml
models:
  User:
    name: string
    email: string unique
    email_verified_at: datetime nullable
    password: string
    remember_token: rememberToken
    softDeletes

controllers:
  User:
    resource
```
