### ISSUE TITLE
Factory failed when type is enum

### ISSUE THREAD

**Issue by berthojoris** [laravel-shift/blueprint#59]
I create my .yaml file
```
models:
  Category:
    category_uuid: string:200
    name: string:200
    status: enum:ACTIVE,NONACTIVE
controllers:
  Category:
    index:
      query: all
      render: category.index with:categories
    create:
      render: category.create
    store:
      validate: category_uuid, name, status
      save: category
      flash: category
      redirect: category.index
    update:
      find: category
      redirect: category.index
    show:
      find: category
      render: category.show with:category
    edit:
      find: category
      render: category.edit with:category
    destroy:
      delete: category.id
      redirect: category.index
```
But when I run, factory file is fail
```
<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Category;
use Faker\Generator as Faker;

$factory->define(Category::class, function (Faker $faker) {
    return [
        'category_uuid' => $faker->word,
        'name' => $faker->name,
        'status' => $faker->,
    ];
});
```
As you see, faker for enum is fail.  Am I missing something?
