### ISSUE TITLE
Controller Short code

### ISSUE THREAD

**Issue by malsgit** [laravel-shift/blueprint#603]
Not a bug or a request and I don't do twitter...!

when using short code on the Controller, how do you get it to generate notification, send or redirect, when doing the following...
```
ControllerName:
     resources: web 
```
is it not something like this, as that seems to break stuff....
```
ControllerName:
    resource: web
    notify: controller_name.user_id
    send: ReviewNotification to:controller_name.user_id with:controller_name
    redirect: controller_name.index
```
