### ISSUE TITLE
Separated enum values are not working well

### ISSUE THREAD

**Issue by muath-ye** [laravel-shift/blueprint#610]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Blueprint Version: #.#.#
- Platform: Mac | Windows | Linux

### Issue:
I have this array of enum `Invoice,Credit Note,Quote,Purchase Order,Receipt` and I can not pass it to the yaml file

### draft.yaml:
```yaml
models:
  Bill:
    currency: string nullable
    type: enum:Invoice,Credit Note,Quote,Purchase Order,Receipt nullable
```

output on the `migration` file

```php
// ...
Schema::create('invoiceas', function (Blueprint $table) {
            $table->id();
            $table->string('currency')->nullable();
            $table->enum('type', ["Invoice","Credit"])->nullable();
// ...
