### ISSUE TITLE
Ability to add connection/table name in model 

### ISSUE THREAD

**Issue by polashsust** [laravel-shift/blueprint#639]
- Laravel Version: 10.4.0
- PHP Version: 8.2.0
- Blueprint Version: 2.7.0
- Platform: Windows

### Issue:
Ability to add connection/table name in model 

### draft.yaml:
```yaml
Models:
    SystemInformationConversion:
         range: string:100
         rubric: string:200
         specified_value: string:50
         softDeletes: true
         timestamps: false

         table: system_information_conversion
         connection: db_connection_name
```
