### ISSUE TITLE
Model attribute called `cast` is being double-quoted in generated code

### ISSUE THREAD

**Issue by GingertronMk1** [laravel-shift/blueprint#640]
- Laravel Version: 10.10
- PHP Version: 8.2.6
- Blueprint Version: 2.7
- Platform: Mac

### Issue:

I have a pre-existing model called `Show`, which has as an attribute an array called `cast`.
When I use blueprint to generate a web resource for this model it double-quotes the word `cast` in the requests and tests generated.
See below for examples.

```
'"cast"' => ['required', 'json'],
```
```
->where('"cast"', $"cast")
```
```
'"cast"' => $"cast",
```

### draft.yaml:
```yaml
models:
  # ...

controllers:
  # ...
    Show:
        resource: web
    Person:
        resource: web
```
