### ISSUE TITLE
Natural Keys For relationships

### ISSUE THREAD

**Issue by inmanturbo** [laravel-shift/blueprint#644]
### Synopsis:
Suppose you have a relationship which uses a natural key, such as a unique phone number, user's email or other user entered data such as an account number

### Proposed Syntax:

```yaml
Transaction:
  account_number: bigint
  relations: 
    belongsTo: Account account_number:number
```
  

### Expected Behavior:

```php
    public function account(): BelongsTo
    {
        return $this->belongsTo(Account::class, 'account_number', 'number');
    }
```

**Comment by ghostwriter** [comment]
Hey @inmanturbo 

I believe the syntax you are looking for is 🤞🏾wrote it from memory:

```yml
models:
  Transaction:
    account_number: foreign:accounts.number
```

which should generate.

```
public function account(): BelongsTo
{
    return $this->belongsTo(Account::class, 'account_number', 'number');
}
```

let me know if it works.

**Comment by inmanturbo** [comment]
Yes that works! Thank you. I didn't see it in the docs anywhere ... :thinking: 

I'll have to have a look at how the docs are built when I get a chance. Maybe I can submit a PR to add it.

**Comment by inmanturbo** [comment]
Unfortunately the migration comes out wrong
Generated outcome is
```php
$table->foreignId('account_number')->constrained();
```

What I'm expecting is

```php

$table->bigint('account_number');
```

**Comment by inmanturbo** [comment]
with something like:

```php
account_number: bigInt foreign:accounts.number
```

and `$use_constraints` set to `false` in `config/blueprint.php`

**Comment by inmanturbo** [comment]
I suppose just removing the constraint would work as well, as `$table->foreignId('account_number');` only implies the relationship and doesn't create the `fk`

**Comment by inmanturbo** [comment]
and lastly, while not what I'm after
```php
$table->foreignId('account_number')->constrained('accounts','number');
```
would be the correctly applied constraint

**Comment by anishsarkar** [comment]
How does one define the reverse relationship in such a case? 
```
models:
  Account: 
    number 
    relationship:
      hasMany: Transaction

  Transaction:
    account_number: foreign:accounts.number

```

does not seem to do it correctly?
