### ISSUE TITLE
A colon cannot be used in an unquoted mapping value

### ISSUE THREAD

**Issue by MosetiReagan** [laravel-shift/blueprint#647]
- Laravel Version: 10.2.4
- PHP Version: 8.01
- Blueprint Version: 2.6
- Platform: Windows

### Issue:
  A colon cannot be used in an unquoted mapping value at line 32 (near "        error: "/generate-certificate"").  

### draft.yaml:
```yaml
routes:
  - url: /generate-certificate
  - controller: CertificateController@index
  - methods:
      - GET
      - POST

models:
  Certificate:
    first_name:
      type: string
      length: 100
    last_name:
      type: string
      length: 100
    template:
      type: string
      length: 100

controllers:
  - name: CertificateController
    resource: true
    requests: true
    methods:
      - name: index
        action: fetch
        view: certificates.index
      - name: generate
        action: create
        redirect:
          success: "/success"
          error: "/generate-certificate"

views:
  - name: certificates.index
    path: resources/views/certificates/index.blade.php
    sections:
      - name: content
        content: "Placeholder text here without HTML"

  - name: success
    path: resources/views/success.blade.php
    sections:
      - name: content
        content: "Placeholder text here without HTML"

requests:
  - StoreCertificateRequest
  - first_name
  - last_name
  - template

migrations: true

factories: true

tests: true


```
