### ISSUE TITLE
issue with Model Keys and Indexes

### ISSUE THREAD

**Issue by devhoussam1998** [laravel-shift/blueprint#650]
- Laravel Version: ^10.10
- PHP Version: ^8.1
- Blueprint Version: ^2.7
- Platform: Mac

### Issue:
first of all I did not find any way to communicate I can't send a message on twitter and there is no **Discussions** that's why I add my question here

`parent_id: foreign:page.parents.id`

**What I get:**

```
public function page(): BelongsTo
{
  return $this->belongsTo(Page::class, 'parent_id', 'parents');
}
```

**expected result:**

```
public function parent(): BelongsTo
{
  return $this->belongsTo(Page::class, 'parent_id');
}
```

### draft.yaml:
```yaml
models:
  Page:
    title: string index
    slug: string unique
    layout: default:default index
    blocks: json
    parent_id: foreign:pages nullable onUpdate:cascade onDelete:cascade
```
