### ISSUE TITLE
Pluralization oddity

### ISSUE THREAD

**Issue by discern** [laravel-shift/blueprint#665]
- Laravel Version: 10.43.0
- PHP Version: 8.3.2
- Blueprint Version: 2.9.0
- Platform: Mac

### Issue:
Blueprint correctly creates a `Regatta` model and a `regattas` table; however, in the `RaceFactory` file, it calls `Regattum::factory()`.

### draft.yaml:
```yaml
models:
  Regatta:
    name: string
    relationships:
      hasMany: Race

  Race:
    regatta_id: id foreign
    result: unsignedSmallInteger nullable
    relationships:
      belongsTo: Regatta

```
