### ISSUE TITLE
Allowing the build command to try to auto-skip

### ISSUE THREAD

**Issue by wotta** [laravel-shift/blueprint#697]
### Synopsis:
At this moment when we run the build command we do have an option to pass a list of file classes, but this somewhat unnatural to me. When I am adding models and other stuff as POC real quick I usually forget to delete the old stuff. 

Imagine I generated a `draft.yaml` with the following content:

```yaml
models:
  Timesheet:
    postal_from: string:6
    house_number_from: string:4
    city_from: string
    postal_to: string:6
    house_number_to: string:4
    city_to: string

seeders: Timesheet
```

Now when quickly used filament and api platform to generate my resources for both the admin and api and I want to add an additional model I usually add it below the existing information. Like below.

```yaml
models:
  Timesheet:
    postal_from: string:6
    house_number_from: string:4
    city_from: string
    postal_to: string:6
    house_number_to: string:4
    city_to: string
  Setting: // This is new
    name: string
    value: text
    model: string
    softDeletes

seeders: Timesheet
```

### Proposed Syntax:
Nothing changes here.

### Expected Behavior:
It would be amazing if I could run for example `php artisan blueprint:build --auto-skip` which would use the `.blueprint` file to automatically add the files generated to the skip option to achieve this behavior.

Let me know if you don't mind this being an additional option to use.
