### ISSUE TITLE
undefined method 'authorize' when generate controller with policy

### ISSUE THREAD

**Issue by burasuk** [laravel-shift/blueprint#701]
- Laravel Version: 11.28.1
- PHP Version: 8.3.4
- Blueprint Version: 2.10.0
- Platform: Windows 

### Issue:
Blueprint generate code that not exists in Laravel 11.    

```
public function index(Request $request)
    {
        $this->authorize('index', Customer::class);// <= here
        $customers = Customer::all();
        return new CustomerCollection($customers);
    }
```                    

### draft.yaml:
```yaml
controllers:
  Customer:
    resource: api.index, api.store, api.show,api.update,api.destroy     
    meta:
      policies: index,store,show,update,destroy
```
