### ISSUE TITLE
Does not support Geography migration data type

### ISSUE THREAD

**Issue by securit** [laravel-shift/blueprint#706]
- Laravel Version: 11.30
- PHP Version: 8.3 2.10 #.#.#
- Platform: Mac 

### Issue:
Documentation states 

> Blueprint supports all of the [available column types](https://laravel.com/docs/migrations#creating-columns) within Laravel.

but it fails to correctly define a geography in the database migrations

### draft.yaml:
```yaml
models:
  Location:
    name:  string:100
    description: nullable text
    coordinates: geography,points
```

Which creates a string for coordinates instead of  a `$table->geography`
```
        Schema::create('locations', function (Blueprint $table) {
            $table->id();
            $table->string('name', 100);
            $table->text('description')->nullable();
            $table->string('coordinates');
```            
instead of
```
        Schema::create('locations', function (Blueprint $table) {
            $table->id();
            $table->string('name', 100);
            $table->text('description')->nullable();
            $table->geography('coordinates', 'point');
```
