### ISSUE TITLE
A question to the maintainer

### ISSUE THREAD

**Issue by tectiv3** [laravel-shift/blueprint#73]
Hey, thank you for your awesome work on blueprint it does wanders.

I've made some `uuid` and API resources work in my fork and was wandering do you want those changes in upstream?
(https://github.com/tectiv3/blueprint/tree/add-api-resources-support)
I can separate uuids, resources generation and foreign keys and indexes support into different PRs if you are interested.
Currently I've added support for uuid and json columns, index modifiers, api controllers, policies, resources generation and foreign keys in migrations.

```yaml
models:
  Order:
    id: uuid primary
    user_id: id foreign:user
    external_id: string nullable index
    subscription_id: uuid foreign:subscription
    sku: string nullable
    status: enum:created,pending,paid,deleted,refunded default:'created'
    expires_at: timestamp nullable index
    meta: json default:'[]'
controllers:
  Order:
    index:
      query: user.all
      resource: order collection:paginate
    store:
      validate: type, name
      save: order
      fire: NewOrder with:order
      resource: order
    show:
      authorize: order
      resource: order
    destroy:
      authorize: order
      delete: order
      resource: empty
  Subscription:
    resource: api
    index:
      query: user.all
      resource: subscription collection:paginate
```

Once again, thank you for creating this tool!
