### ISSUE TITLE
There is Wrong Route Model Binding in Controller 

### ISSUE THREAD

**Issue by aip-jit** [laravel-shift/blueprint#744]
- Laravel Version: 11.43.2
- PHP Version: 8.3.17
- Blueprint Version: 2.11
- Platform:  Linux

### Issue:using route model binding (User $user in the method signature) but then trying to manually find the user with User::find($id). However, $id is not defined in your function.
public function edit(Request $request, User $user): View
    {
        $user = User::find($id);

        return view('user.edit', [
            'user' => $user,
        ]);
    }
 other functions also same issue 

### draft.yaml:
```yaml
# PLEASE PASTE THE DRAFT FILE WHICH REPRODUCES THE ISSUE HERE...
models:
  User:
    id: bigIncrements
    name: string:100
    phone_number: string:15
    email: string:150 unique
    email_verified_at: timestamp nullable
    password: string:255
    remember_token: string:100 nullable
    deleted_at: timestamp nullable
    timestamps: true

controllers:
  UserController:
    index:
      query: all
      render: user.index with:users
    show:
      find: id
      render: user.show with:user
    create:
      render: user.create
    store:
      validate: name, phone_number, email, password
      save: user
      redirect: user.index
    edit:
      find: id
      render: user.edit with:user
    update:
      find: id
      validate: name, phone_number, email, password
      update: user
      redirect: user.index
    destroy:
      find: id
      delete: user
      redirect: user.index

```
