### ISSUE TITLE
alternative belongsToMany relationship name not working

### ISSUE THREAD

**Issue by brunomdsilva** [laravel-shift/blueprint#745]
- Laravel Version: 11
- PHP Version: 8.2
- Blueprint Version: 2.11
- Platform: Mac

### Issue:
`belongsToMany` relationship not using alternative name as pivot relationship name

### draft.yaml:
```yaml
  Customer:
    name: string
    relationships:
      belongsToMany: Pet

  Pet:
    name: string
    relationships:
      belongsToMany: Customer:owner
```

### Genrated Code:
```php
# Models/Pet
  
# "customers" here should be "owners"
public function customers(): BelongsToMany
  {
      return $this->belongsToMany(Customer::class, 'owner');
  }
```
