### ISSUE TITLE
Nullable json column produces nullable string

### ISSUE THREAD

**Issue by salamwaddah** [laravel-shift/blueprint#750]
- Laravel Version: 12.14.1
- PHP Version: 8.3
- Blueprint Version: 2.12
- Platform: Mac

### Issue:
nullable json columns is producing `$table->string('column_name')->nullable();` it is also missing the model casting to `array`. However it behaves like expected when it's not nullable

### draft.yaml:
```yaml
  MeatCut:
    slug: string, unique
    animal_id: id foreign
    name: string
    alt_names: json, nullable
    description: text
```
