### ISSUE TITLE
id: false doesn't disable the id column

### ISSUE THREAD

**Issue by justinwhite15** [laravel-shift/blueprint#85]
Documentation states:

> By default, each model will automatically be defined with an id and timestamps columns. To disable these columns you may define them with a false value. For example, timestamps: false.

But adding `id: false` to a model's definition in the YAML doesn't disable the creation of the id column in the migration.

To reproduce, use the .yaml below:
```yaml
models:
  Phone:
    id: false
    label: string
    user_id: id
    phone_number: text
    type: enum:home,cell
    status: set:archived,deleted
    timestamps: false
```

This will generate the migration below:
```php
        Schema::create('phones', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('label');
            $table->unsignedBigInteger('user_id');
            $table->text('phone_number');
            $table->enum('type', ["home","cell"]);
            $table->set('status', ["archived","deleted"]);
        });
```

I took a quick look through the code, and although the Model model does include a usesTimestamps() method, it doesn't have a usesId() method.

Options
1. I am using the wrong YAML
2. Update the documentation to indicate that the id field cannot be disabled
3. Update the code to allow for an id field to be not generated.

@jasonmccreary Do you have a preference? Or, did I miss something?
