### ISSUE TITLE
Clarify Resource Controller Documentation in README.md

### ISSUE THREAD

**Issue by defenestrator** [laravel-shift/blueprint#89]
There's no documentation on how to generate Resource Controllers, but they are "encouraged" by the readme. I figured I'd add a note to include this with another merge or make some updates to docs in a  dedicated PR. Loving it, JMac!
```yaml
controllers:
  Comment:
    resource
```
