### ISSUE TITLE
Generate Resource data based on Model

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/blueprint#94]
Currently, only the class "stub" is generate for a Resource.

Given that the `resource` statement referenced a model, it would be nice to generate the return value of the `toArray` for all of the _non-hidden_ columns of the model.

**Comment by nathane** [comment]
How do you want users to generate `hidden` columns/attributes for a Model?

```
models:
  User:
    email: string
    password: string hidden
    remember_token: string hidden
```
